/**
 * iOS: `FlowPracticesMainTabChromeCopy.swift` — главный TabView, Flow, Practices.
 * Меняем текст здесь → дословно в Swift.
 */

export type FlowPracticesChromeLocale = "ru" | "en";

export const TODAY_MAIN_TAB_COPY_RU = {
  "today": "Сегодня",
  "flow": "Flow",
  "profile": "Профиль",
  "compatibility": "Совместимость",
  /** Паритет `nav.header.guidance` в `CONTENT/i18n/app.ru.json`. */
  "guidance": "Разбор"
} as const;
export const TODAY_MAIN_TAB_COPY_EN = {
  "today": "Today",
  "flow": "Flow",
  "profile": "Profile",
  "compatibility": "Compatibility",
  "guidance": "Guidance"
} as const;

export const FLOW_TRACKER_CHROME_RU = {
  "affirmationsCatalogEmpty": "Каталог не загрузился или пуст. Следующий шаг — отдельный нативный каталог.",
  "affirmationsCatalogCountEn": "{{n}} item",
  "affirmationsCatalogCountEnPlural": "{{n}} items",
  "affirmationsCatalogCountRu1": "{{n}} позиция",
  "affirmationsCatalogCountRu24": "{{n}} позиции",
  "affirmationsCatalogCountRuMany": "{{n}} позиций",
  "affirmationsCatalogSectionTitle": "Каталог",
  "affirmationsCtaMoveToday": "Перенести в Today",
  "affirmationsCtaOpenPractices": "Открыть практики",
  "affirmationsCtaOpenToday": "Открыть Today",
  "affirmationsCtaOpenTracker": "Открыть карту",
  "affirmationsCtaSignInToday": "Войти и открыть Today",
  "affirmationsCtaSignInUse": "Войти и использовать",
  "affirmationsDefaultTitleAffirmation": "Аффирмация",
  "affirmationsDefaultTitleMantra": "Мантра",
  "affirmationsEmptyFilterHint":
    "По этим условиям пока ничего не найдено. Попробуй снять часть фильтров или задать более широкий запрос.",
  "affirmationsFeaturedSectionTitle": "Сейчас может откликнуться",
  "affirmationsFocusCalmHint": "Собраться, выдохнуть, не расплескать себя.",
  "affirmationsFocusCalmTitle": "Спокойствие",
  "affirmationsFocusGrowthHint": "Развитие, смелость и движение дальше.",
  "affirmationsFocusGrowthTitle": "Рост",
  "affirmationsFocusLoveHint": "Контакт, близость, открытость и доверие.",
  "affirmationsFocusLoveTitle": "Отношения",
  "affirmationsFocusMoneyHint": "Опора, изобилие, материальная устойчивость.",
  "affirmationsFocusMoneyTitle": "Деньги",
  "affirmationsFocusSupportHint": "Мягкий внутренний голос и восстановление.",
  "affirmationsFocusSupportTitle": "Поддержка",
  "affirmationsFocusWorkHint": "Роль, реализация, решение и действие.",
  "affirmationsFocusWorkTitle": "Работа",
  "affirmationsFocusAllHint": "Полная библиотека фраз и опор.",
  "affirmationsFocusAllTitle": "Все темы",
  "affirmationsKindLabelAffirmation": "Аффирмация",
  "affirmationsKindLabelMantra": "Мантра",
  "affirmationsKindFilterAffirmation": "Аффирмации",
  "affirmationsKindFilterAll": "Всё",
  "affirmationsKindFilterMantra": "Мантры",
  "affirmationsLibraryLinkAllTrackers": "Все карты",
  "affirmationsLibraryLoadError": "Не удалось загрузить библиотеку.",
  "affirmationsLibraryPageEyebrow": "Библиотека",
  "affirmationsLibraryPageLead":
    "Здесь собраны короткие фразы и опорные формулы, которые помогают собраться, удержать состояние, пройти напряжённый момент или мягко закрепить новый внутренний ход.",
  "affirmationsLibraryPageTitle": "Библиотека аффирмаций и мантр",
  "affirmationsLibraryLinkTracker": "Карта аффирмаций",
  "affirmationsMantraPronunciationPrefix": "Произношение: {{text}}",
  "affirmationsPersonalBadge": "Персонально",
  "affirmationsPersonalCta": "Подобрать 3 формулировки",
  "affirmationsPersonalEmptyHint": "Здесь появятся дополнительные формулировки под выбранную тему.",
  "affirmationsPersonalGenerating": "Собираем...",
  "affirmationsPersonalSectionBody":
    "Если хочется не только библиотеку, но и несколько свежих фраз под текущую тему, можно собрать их отдельно.",
  "affirmationsPersonalSectionTitle": "Личные формулировки",
  "affirmationsSearchPlaceholder": "Поиск по словам, состоянию, теме или смыслу...",
  "affirmationsTrackerBackToAllTrackers": "← Все карты",
  "affirmationsTrackerBackToCatalog": "← Каталог аффирмаций",
  "affirmationsTrackerEntryNotUsed": "○ Не использовано",
  "affirmationsTrackerEntryStateLabel": "Состояние:",
  "affirmationsTrackerEntryUsed": "✓ Использовано",
  "affirmationsTrackerLoginPrompt": "Войдите, чтобы открыть карту аффирмаций.",
  "affirmationsTrackerNewEntryTitle": "Новая запись",
  "affirmationsTrackerNoEntriesForDate": "Нет записей за эту дату",
  "affirmationsTrackerNoteLabel": "Заметка (опционально)",
  "affirmationsTrackerNotePlaceholder": "Короткая заметка…",
  "affirmationsTrackerPageLead":
    "Короткие фразы для закрепления состояния. Выбери одну аффирмацию на день и отметь использование.",
  "affirmationsTrackerScaleLabel": "Шкала состояния (1–5)",
  "affirmationsTrackerSelectLabel": "Аффирмация (короткая фраза)",
  "affirmationsTrackerSelectPlaceholder": "Выберите аффирмацию",
  "affirmationsTrackerStateLabel": "Состояние (1–2 слова)",
  "affirmationsTrackerStatePlaceholder": "например: спокойно, сфокусированно",
  "affirmationsTrackerToastPickAffirmation": "Выберите аффирмацию",
  "affirmationsTrackerUsedLabel": "Использовано",
  "affirmationsSyncNote": "Отметки на выбранный день — через тот же журнал, что и на сайте.",
  "affirmationsTitle": "Аффирмации",
  "actionCancel": "Отмена",
  "actionSave": "Сохранить",
  "asceticCatalogEmpty": "Каталог аскез пуст или недоступен.",
  "asceticDurationPicker": "Срок",
  "asceticDurationSection": "Срок",
  "asceticFallbackTitle": "Аскеза",
  "asceticLoadingCatalog": "Загружаю каталог…",
  "asceticNavTitle": "Аскеза",
  "asceticPracticeSection": "Практика",
  "asceticsEmpty": "Пока нет активных аскез для отметки. Создай контракт через Today: «Собрать день» → чип «эмоции».",
  "asceticsSyncNote": "Отметка дня — тот же запрос, что и на сайте.",
  "asceticsTitle": "Аскезы",
  "balance": "Баланс",
  "calendarFailed": "Календарь не загрузился",
  "close": "Закрыть",
  "completeGoal": "Завершить",
  "connectionHeader": "Подключение",
  "create": "Создать",
  "createContract": "Создать контракт",
  "dayTracker": "Ход дня",
  "diaryEasierPlaceholder": "1–2 предложения о том, что оказалось легче…",
  "diaryEasierPrompt": "Что прошло мягче, чем ожидалось",
  "diaryEasierTitle": "Что оказалось легче",
  "diaryHardestPlaceholder": "1–2 предложения о том, где было сложнее всего…",
  "diaryHardestPrompt": "Где день начал распадаться",
  "diaryHardestTitle": "Где было сложнее всего",
  "diaryIntro": "Без анализа и драматизации: что заметила, где было сложнее, что оказалось легче.",
  "diaryNoticedPlaceholder": "1–2 предложения о том, что заметил…",
  "diaryNoticedPrompt": "1–2 предложения о главном наблюдении",
  "diaryNoticedTitle": "Что заметила",
  "diaryTitle": "Дневник наблюдений",
  "done": "Сделано",
  "energy": "Энергия",
  "focus": "Фокус",
  "generateInsight": "Сгенерировать инсайт",
  "generatingInsight": "Собираем инсайт",
  "insightsGenerateErrorFallback": "Ошибка при генерации инсайта",
  "insightsGeneratingShort": "Генерация...",
  "goalLimitReached": "Уже 3 цели на этот период — заверши или смени период.",
  "goalQuickPeriodNote": "Период привязан к выбранному дню в календаре Flow — как на сайте.",
  "goalSheetTitle": "Цель",
  "goalsNavTitle": "Цели",
  "goalsPickDateHint": "Выбери дату на вкладке «Календарь», затем отметь шаг цели для этого дня.",
  "habitCadence": "Частота",
  "habitCategory": "Категория (как в веб-мастере)",
  "habitDaily": "Каждый день",
  "habitIdeas": "Идеи",
  "habitSheetTitle": "Привычка",
  "habitWeekly": "Несколько раз в неделю",
  "habitsEmpty": "Пока нет активных привычек — добавь первую ниже.",
  "habitsMapAddCreating": "Создание...",
  "habitsMapAddCta": "Добавить привычку",
  "habitsMapAddSectionTitle": "Добавить привычку",
  "habitsMapCategoryPlaceholder": "Категория: body / focus / mind",
  "habitsMapCheckErrorFallback": "Не удалось отметить привычку",
  "habitsMapCreateErrorFallback": "Ошибка создания привычки",
  "habitsMapEmptyList": "Привычек пока нет. Создай первую привычку выше.",
  "habitsMapEyebrow": "Карта привычек",
  "habitsMapHeroBody":
    "Здесь привычки не спорят с аскезами и практиками. Это отдельный слой дисциплины: повторяемые действия, мягкая визуализация ритма и понятная сводка.",
  "habitsMapHeroTitle": "Карта привычек без лишнего шума",
  "habitsMapHowToReadLine1":
    "Каждая привычка показывает свой ритм за последние 28 дней через мягкую heatmap-ленту.",
  "habitsMapHowToReadLine2":
    "Отметка сегодня нужна не ради «галочки», а чтобы видеть, какие действия реально держат твой день.",
  "habitsMapHowToReadTitle": "Как читать карту",
  "habitsMapLinkCalendar": "К календарю",
  "habitsMapLinkToday": "К Today",
  "habitsMapLinkTrackingHub": "Мои карты",
  "habitsMapLoadErrorFallback": "Не удалось загрузить карту привычек",
  "habitsMapLoginLead":
    "Войди, чтобы выстроить личный ритм и видеть, как складывается история — без таблиц и процентов.",
  "habitsMapMarkedToday": "Отмечено",
  "habitsMapMarkToday": "Отметить сегодня",
  "habitsMapNamePlaceholder": "Например: 10 минут дыхания",
  "habitsMapNoCategory": "без категории",
  "habitsMapPageTitle": "Карта привычек",
  "habitsMapStatsCompact": "{{streak}} дней подряд на карте",
  "habitsMapStatsPending": "История только начинается",
  "habitsMapStrongestRhythm": "Самый сильный текущий ритм: {{name}}, стрик {{days}} дн.",
  "habitsMapStrongestRhythmEmpty":
    "Когда появятся первые отметки, здесь будет виден самый устойчивый ритм.",
  "habitsMapSummary30Empty": "Сводка появится после первых отметок.",
  "habitsMapSummary30Title": "Сводка за 30 дней",
  "habitsMapSummaryStreakLabel": "Стрик:",
  "habitsMapTodayProgress": "{{done}} из {{total}} привычек отмечено",
  "habitsMapTodaySnapshotEyebrow": "Сегодняшний срез",
  "habitsSyncNote": "Отметки на выбранный день совпадают с сайтом.",
  "habitsTitle": "Привычки",
  "heatmapDrillAsceticsLinePrefix": "Аскезы (удержано):",
  "heatmapDrillDayEyebrow": "День",
  "heatmapDrillGoalsLinePrefix": "Цели:",
  "heatmapDrillHabitsLinePrefix": "Привычки:",
  "heatmapDrillPracticeDone": "выполнена",
  "heatmapDrillPracticeLabel": "Практика:",
  "heatmapDrillPracticeNo": "нет",
  "heatmapDrillTotalsPrefix": "Всего на карте:",
  "heatmapDrillDayCaptionEmptyTracks": "Нет активных треков — добавь цель, привычку или аскезу.",
  "heatmapDrillDayCaptionGoalsNoStep": "Не было шага по целям — имеет смысл один конкретный шаг по выбранной цели.",
  "heatmapDrillDayCaptionPartialDay": "Частично закрыто — видно, куда ещё можно добить.",
  "heatmapDrillDayCaptionQuietDay": "Слабый день — почти без движения по трекам.",
  "heatmapDrillDayCaptionStrongDay": "Плотный день — хорошая опора по трекам.",
  "heatmapEntityPickHint": "Выбери сущность в списке — иначе показывается сводно по типу.",
  "heatmapEntityPickPlaceholder": "Выбери…",
  "heatmapUnderMapInsightAllFreeGaps": "Есть провалы в сетке — это нормально, если заметить их.",
  "heatmapUnderMapInsightAllFreeSteady": "Ритм в целом ровный по выбранному фильтру.",
  "heatmapUnderMapInsightAllPremiumReadable": "Паттерн месяца читается: видно, где ты набираешь плотность.",
  "heatmapUnderMapInsightAllPremiumStutter": "Ты держишься несколько дней, затем проседаешь — нет устойчивого ритма на весь месяц.",
  "heatmapUnderMapInsightAllProSteady": "Картина относительно ровная — мало резких провалов.",
  "heatmapUnderMapInsightAllProVolatile": "Ритм нестабильный: плотные дни чередуются с пустыми.",
  "heatmapUnderMapInsightAsceticsFreeGaps": "По аскезам есть дни без удержания.",
  "heatmapUnderMapInsightAsceticsFreeSteady": "По аскезам плотность выше.",
  "heatmapUnderMapInsightAsceticsPremium": "Если после насыщенных зон идёт резкий спад — правило может быть жёстким.",
  "heatmapUnderMapInsightAsceticsPro": "Срывы видны как пустые или очень светлые клетки подряд.",
  "heatmapUnderMapInsightGoalsFreeGaps": "По целям есть дни без шага.",
  "heatmapUnderMapInsightGoalsFreeSteady": "По целям движение заметнее.",
  "heatmapUnderMapInsightGoalsPremium": "Ты не двигаешься по целям регулярно — нет ежедневных шагов; упрости до одного шага в день.",
  "heatmapUnderMapInsightGoalsPro": "Цели без ежедневных шагов дают «рваную» сетку.",
  "heatmapUnderMapInsightHabitsFreeGaps": "По привычкам есть светлые дни.",
  "heatmapUnderMapInsightHabitsFreeSteady": "Привычки выглядят стабильнее.",
  "heatmapUnderMapInsightHabitsPremium": "Поведенческий слой: выходные или конец недели часто светлее — проверь триггеры.",
  "heatmapUnderMapInsightHabitsPro": "Привычки могут быть не закреплены — смотри на «дырявые» недели.",
  "heatmapUnderMapInsightPracticesFreeGaps": "Системные практики не закрываются каждый день.",
  "heatmapUnderMapInsightPracticesFreeSteady": "Практики чаще отмечены.",
  "heatmapUnderMapInsightPracticesPremium": "Сравни с ALL: если практики ровные, а ALL рваный — упор на цели и привычки.",
  "heatmapUnderMapInsightPracticesPro": "Практика одна на день — сетка показывает дисциплину «да/нет».",
  "heatmapFilterGoalsRowTitle": "Цели (пусто = все активные)",
  "heatmapInsightPrefix": "Инсайт",
  "heatmapJumpToCurrentMonth": "К текущему",
  "heatmapLegendEntityDone": "сделано",
  "heatmapLegendEntityMiss": "нет",
  "heatmapLegendIntensity0": "тише",
  "heatmapLegendIntensityHigh": "ярче",
  "heatmapLegendIntensityLow": "легче",
  "heatmapLegendIntensityMid": "ровно",
  "heatmapLegendNoData": "нет данных",
  "heatmapMapExplainer": "Один день — одна клетка. Цвет показывает, насколько плотным был день по выбранной линии. Серый — нет данных или будущее. Без цифр внутри.",
  "heatmapModeAll": "ALL",
  "heatmapNextMonthA11y": "Следующий месяц",
  "heatmapPrevMonthA11y": "Предыдущий месяц",
  "heatmapRowModeAggregate": "Сводно (доля)",
  "heatmapRowModeLabel": "Режим строки:",
  "heatmapRowModeOneEntity": "Одна сущность",
  "heatmapSelectAllShort": "все",
  "heatmapUnderMapEyebrowPrefix": "Под картой",
  "horizonPicker": "Горизонт",
  "insightsEmpty": "За эту дату инсайтов пока нет. Добавь 1-2 отметки и нажми «Сгенерировать инсайт».",
  "insightsIntro": "Инсайт собирается из отметок календаря и дневника за выбранный день.",
  "insightsTitle": "Автоинсайты",
  "trackingDiaryEasierFieldLabel": "Что оказалось легче, чем ожидал",
  "trackingDiaryEntryFormTitle": "Запись наблюдений",
  "trackingDiaryFillAtLeastOne": "Заполните хотя бы одно поле",
  "trackingDiaryHardestFieldLabel": "Где было сложнее всего",
  "trackingDiaryLoginPrompt": "Войдите, чтобы использовать дневник наблюдений",
  "trackingDiaryNoticedFieldLabel": "Что я заметил",
  "trackingDiaryPageIntro":
    "Не анализ, а отражение. Что заметил, где было сложнее всего, что оказалось легче. Без выводов, без «почему» — просто наблюдение.",
  "trackingDiaryReadoutEasier": "Что оказалось легче:",
  "trackingDiaryReadoutHardest": "Где было сложнее всего:",
  "trackingDiaryReadoutNoticed": "Что заметил:",
  "trackingDiarySaveError": "Ошибка при сохранении",
  "trackingDiaryEntriesHeading": "Записи за {{date}}",
  "trackingFormDateLabel": "Дата",
  "trackingInsightConfidenceHigh": "Высокая уверенность",
  "trackingInsightConfidenceLow": "Низкая уверенность",
  "trackingInsightConfidenceMedium": "Средняя уверенность",
  "trackingInsightDataAvgMood": "Тон этих дней:",
  "trackingInsightDataClearDecisions": "Ясных решений:",
  "trackingInsightDataDaysReviewed": "Дней в анализе:",
  "trackingInsightDataDominantFocus": "Доминирующий фокус:",
  "trackingInsightDataEntries": "Записей:",
  "trackingInsightDataGatheredDays": "Собранных дней:",
  "trackingInsightDataRepeatCount": "Повторений:",
  "trackingInsightDataTotalCountSuffix": "{{n}} всего",
  "trackingInsightDataUngatheredDays": "Несобранных дней:",
  "trackingInsightDataUnclearDecisions": "Неясных решений:",
  "trackingInsightDataWeekendEntries": "Выходных записей:",
  "trackingInsightTypeCorrelation": "Корреляция",
  "trackingInsightTypePattern": "Паттерн",
  "trackingInsightTypeShift": "Сдвиг",
  "trackingInsightTypeSignalClarity": "Ясность решения",
  "trackingInsightTypeSignalClosure": "Собранность дня",
  "trackingInsightTypeSignalFocus": "Повторяющийся фокус",
  "trackingInsightTypeStreak": "Стрик",
  "trackingInsightTypeWeekendPattern": "Паттерн выходных",
  "trackingInsightsEmptyHint": "Нажми «Сгенерировать инсайт» и добавь 1-2 отметки за день.",
  "trackingInsightsEmptyTitle": "Нет инсайтов за эту дату.",
  "trackingInsightsLoginPrompt": "Войдите, чтобы видеть автоматические инсайты",
  "trackingInsightsPageLead": "Здесь ты видишь короткие наблюдения за день и следующий практичный шаг.",
  "trackingInsightsPageTitle": "Автоматические инсайты",
  "loadingBootstrap": "Загружаю календарь и карты...",
  "logPractice": "Отметить практику",
  "markStep": "Отметить шаг",
  "monthMapTitle": "Карта месяца",
  "monthStatsTitle": "Этот месяц в цифрах",
  "monthSubtitle": "Выбери день и отметь шаги по целям, привычкам и практикам.",
  "nameFieldPlaceholder": "Название",
  "navFlow": "Flow",
  "newGoal": "Новая цель",
  "newHabit": "Новая привычка",
  "noGoalsYet": "Пока нет целей — создай выше.",
  "noMarksDay": "За этот день пока нет отметок.",
  "openCalendarForDay": "Открыть календарь для отметок дня",
  "openGoals": "Открыть цели",
  "pickDayOnMap": "Выбери день на карте месяца.",
  "practiceDoneLabel": "Отмечено на этот день",
  "practiceHint": "Быстрая отметка, как на сайте. Снять её здесь нельзя — только в разделе практик.",
  "practiceTitle": "Практика",
  "reopenGoal": "Снова в работе",
  "retry": "Повторить",
  "rhythmEncouragementFallback": "Ритм недели уже виден по накопленным дням.",
  "saveDiary": "Сохранить запись",
  "saveDiarySaving": "Сохранение...",
  "savedForDay": "Сохранено на день",
  "selectedDay": "Выбранный день",
  "statFullCheckins": "Полные отметки",
  "statGoalDays": "Дни с целями",
  "statHabitDays": "Дни с привычками",
  "stepsForDay": "Шаги для этого дня",
  "streaksNow": "Серии сейчас",
  "summaryEasier": "Легче, чем ожидалось",
  "summaryHardest": "Сложнее всего",
  "summaryNoticed": "Заметила",
  "syncIssueTitle": "Проблема синхронизации",
  "trackerAlertTitle": "Карты",
  "trackingCalendarEmptyState": "Нет данных календаря.",
  "trackingCalendarLoginPrompt": "Войдите, чтобы открыть карты.",
  "trackingCalendarPageEyebrow": "Карты",
  "trackingCalendarPageIntro": "Здесь видно, как день за днем складываются цели, привычки и практики. Один экран — вся картина твоего ритма.",
  "trackingCalendarPageTitle": "Flow: ритм и действия",
  "trackingCategoryAsceticEmpty": "аскез нет",
  "trackingCategoryAsceticMixed": "есть срывы, но трек живой",
  "trackingCategoryAsceticStrong": "удерживаешь правила",
  "trackingCategoryAsceticWeak": "много остановок или срывов",
  "trackingCategoryGoalEmpty": "целей пока нет",
  "trackingCategoryGoalMixed": "есть движение, но не по всем",
  "trackingCategoryGoalOverloaded": "целей слишком много для устойчивого ритма",
  "trackingCategoryGoalStrong": "по целям есть движение",
  "trackingCategoryGoalWeak": "много застоя по целям",
  "trackingCategoryHabitEmpty": "привычек нет",
  "trackingCategoryHabitMixed": "кто-то держится, кто-то плавает",
  "trackingCategoryHabitStrong": "большинство держится",
  "trackingCategoryHabitWeak": "много брошенных или слабых линий",
  "trackingCategoryPracticeActive": "выполняешь предложенное",
  "trackingCategoryPracticeEmpty": "практики не подключены",
  "trackingCategoryPracticeIgnored": "системные практики игнорируются",
  "trackingCategoryPracticeNeutral": "иногда делаешь",
  "trackingCatSummaryAsceticsCounts": "{{total}} активные · {{holding}} держится · {{broken}} сорвалась",
  "trackingCatSummaryAsceticsZero": "0 активных",
  "trackingCatSummaryGoalsCounts": "{{total}} активные · {{inProgress}} в прогрессе · {{stalled}} в застое",
  "trackingCatSummaryGoalsZero": "0 активных",
  "trackingCatSummaryHabitsCounts": "{{total}} активные · {{holding}} держатся · {{unstable}} нестабильны",
  "trackingCatSummaryHabitsZero": "0 активных",
  "trackingCatSummaryPracticesActive": "выполняется",
  "trackingCatSummaryPracticesEmpty": "система предлагает практики",
  "trackingCatSummaryPracticesIgnored": "игнорируется",
  "trackingCatSummaryPracticesNeutral": "иногда",
  "trackingCatSummaryPracticesPrefix": "система предлагает 1 · ",
  "trackingAttentionAsceticBreaksLine": "есть срывы",
  "trackingAttentionAsceticFailedLine": "{{count}} срывов (окно 7 дн.)",
  "trackingAttentionGoalStalledLine": "застой {{days}} дн.",
  "trackingAttentionHabitDroppedLine": "брошена · без отметок {{days}} дн.",
  "trackingAttentionUnstableShort": "нестабильно",
  "trackingBestAsceticHoldLine": "держишься {{n}} дн.",
  "trackingBestGoalSteps5dLine": "{{n}} шага за 5 дней",
  "trackingBestHabitStreakLine": "{{n}} дней подряд",
  "trackingEntityWizardAsceticCatalogLoadError": "Не удалось загрузить каталог аскез",
  "trackingEntityWizardAsceticCreatedSuccess": "Аскеза зафиксирована",
  "trackingEntityWizardAsceticDirectionLabel": "Направление",
  "trackingEntityWizardAsceticDurationContractLabel": "Длительность контракта",
  "trackingEntityWizardAsceticDurationDays14": "14 дней",
  "trackingEntityWizardAsceticDurationDays21": "21 день",
  "trackingEntityWizardAsceticDurationDays30": "30 дней",
  "trackingEntityWizardAsceticDurationDays7": "7 дней",
  "trackingEntityWizardAsceticDurationOpen": "Без срока",
  "trackingEntityWizardAsceticEmptyCategoryHint":
    "В этой категории ничего не нашлось — выбери «Все».",
  "trackingEntityWizardAsceticEndOpenHint": "Дата окончания не задана — контракт открытый",
  "trackingEntityWizardAsceticEndUntil": "До {{date}} включительно",
  "trackingEntityWizardAsceticKindDesc": "Осознанное ограничение по контракту",
  "trackingEntityWizardAsceticKindTitle": "Аскеза",
  "trackingEntityWizardBack": "Назад",
  "trackingEntityWizardCategoryLabel": "Категория",
  "trackingEntityWizardCreateCta": "Создать",
  "trackingEntityWizardCustomVariantLabel": "Свой вариант",
  "trackingEntityWizardGoalCreatedSuccess": "Цель добавлена",
  "trackingEntityWizardGoalKindDesc": "Фокус на неделю или месяц, шаги в календаре",
  "trackingEntityWizardGoalKindTitle": "Цель",
  "trackingEntityWizardHabitCreatedSuccess": "Привычка создана",
  "trackingEntityWizardHabitKindDesc": "Повторяющееся действие с ритмом день/неделя",
  "trackingEntityWizardHabitKindTitle": "Привычка",
  "trackingEntityWizardHabitWeeklyTargetLabel": "Раз в неделю (цель)",
  "trackingEntityWizardHabitWeeklyTimes": "{{n}} раз",
  "trackingEntityWizardLoadingAsceticCatalog": "Загрузка каталога…",
  "trackingEntityWizardNeedTitleOrPick": "Введите название или выберите вариант",
  "trackingEntityWizardNextTimings": "Дальше: сроки",
  "trackingEntityWizardPeriodLabel": "Период",
  "trackingEntityWizardPlaceholderCustomTitle": "Коротко сформулируй цель или привычку",
  "trackingEntityWizardRhythmLabel": "Ритм",
  "trackingEntityWizardSaveFailed": "Не удалось сохранить",
  "trackingEntityWizardSaving": "Сохраняем…",
  "trackingEntityWizardStartLabel": "Старт",
  "trackingEntityWizardStepPickKind": "Что добавляем?",
  "trackingEntityWizardStepPickVariant": "Выбор варианта",
  "trackingEntityWizardStepProgress": "Шаг {{step}} из 3",
  "trackingEntityWizardStepTimingsCreate": "Сроки и создание",
  "trackingEntityWizardMonthFrom": "Месяц (с {{date}})",
  "trackingEntityWizardWeekFrom": "Неделя (с {{date}})",
  "trackingFooter": "Здесь собирается история твоего ритма.",
  "trackingMarkTodayAfterSave": "Сегодня засчитан",
  "trackingMarkTodayFab": "Отметить сегодня",
  "trackingMarkTodayFabEmpty": "Отметь первый день",
  "trackingMarkTodayModalTitle": "Сегодня",
  "trackingProgressCardAffirmationsDesc": "Отдельный поток для аффирмаций.",
  "trackingProgressCardAffirmationsTitle": "Карта аффирмаций",
  "trackingProgressCardAsceticClassicDesc": "Альтернативный экран только для отметок по аскезам — если привык к старому сценарию.",
  "trackingProgressCardAsceticClassicTitle": "Карта аскез (классический вид)",
  "trackingProgressCardHabitsListDesc": "Расширенный обзор и история — создание дублирует календарный мастер.",
  "trackingProgressCardHabitsListTitle": "Карта привычек",
  "trackingProgressCardMainCalendarDesc": "Главная точка: карта месяца, цели, привычки, аскезы и практики. Создание целей, привычек и контрактов аскез — прямо здесь, без переходов.",
  "trackingProgressCardMainCalendarTitle": "Карта ритма",
  "trackingProgressCardQuickAsceticDesc": "Выбор из каталога и срок контракта.",
  "trackingProgressCardQuickAsceticTitle": "Быстро: новая аскеза",
  "trackingProgressCardQuickGoalDesc": "Откроется календарь с мастером создания цели.",
  "trackingProgressCardQuickGoalTitle": "Быстро: новая цель",
  "trackingProgressCardQuickHabitDesc": "Мастер привычки с подборкой шаблонов.",
  "trackingProgressCardQuickHabitTitle": "Быстро: новая привычка",
  "trackingProgressFooterAffirmationsLibrary": "Библиотека аффирмаций и мантр",
  "trackingProgressFooterAsceticCatalog": "Каталог аскез",
  "trackingProgressHubEyebrow": "История",
  "trackingProgressHubIntro": "Здесь собраны карты твоей жизни: ритм месяца, привычки, аскезы и аффирмации. Каждый день в Today добавляет новые точки — узор складывается сам.",
  "trackingProgressHubLoginBody": "Войдите, чтобы открыть карты ритма, привычек, аскез и аффирмаций.",
  "trackingProgressHubLoginCta": "Войти",
  "trackingProgressHubLoginTitle": "Мои карты",
  "trackingProgressHubTitle": "Мои карты",
  "trackingScreenHeroDroppedSub": "Большая часть треков без движения — вернись к простому шагу.",
  "trackingScreenHeroDroppedTitle": "Много линий без опоры",
  "trackingScreenHeroEmptySub": "Добавь цель, привычку или аскезу — тогда появится общая картина.",
  "trackingScreenHeroEmptyTitle": "Начни с одной линии",
  "trackingScreenHeroInFlowSub": "Держишь то, что взял на себя.",
  "trackingScreenHeroInFlowTitle": "Ты в ритме",
  "trackingScreenHeroOverloadedSub": "Активных треков слишком много, удерживать всё сложно.",
  "trackingScreenHeroOverloadedTitle": "Ты перегружен",
  "trackingScreenHeroUnstableSub": "Часть линий держится, часть уже просела.",
  "trackingScreenHeroUnstableTitle": "Ты теряешь ритм",
  "trackingStatusAsceticBreaks": "есть срывы",
  "trackingStatusAsceticFailed": "срывы подряд",
  "trackingStatusAsceticHolding": "держишься",
  "trackingStatusAsceticStopped": "остановлена",
  "trackingStatusGoalActiveProgress": "в прогрессе",
  "trackingStatusGoalCompleted": "завершена",
  "trackingStatusGoalStalled": "застой",
  "trackingStatusGoalUnstable": "нестабильно",
  "trackingStatusHabitActive": "держится",
  "trackingStatusHabitDropped": "брошена",
  "trackingStatusHabitUnstable": "нестабильно",
  "trackingToastAsceticLogError": "Не удалось сохранить отметку аскезы.",
  "trackingToastGoalCompleteError": "Не удалось завершить цель.",
  "trackingToastGoalCompleteSuccess": "Цель отмечена выполненной.",
  "trackingToastGoalNameEmpty": "Название не может быть пустым.",
  "trackingToastGoalRenameError": "Не удалось сохранить название.",
  "trackingToastGoalRenameSuccess": "Название цели обновлено.",
  "trackingToastGoalStepDuplicate": "Шаг по этой цели за этот день уже отмечен.",
  "trackingToastGoalStepError": "Не удалось отметить шаг по цели.",
  "trackingToastHabitActive": "Привычка снова активна.",
  "trackingToastHabitPaused": "Привычка на паузе.",
  "trackingToastHabitRenameSuccess": "Название привычки обновлено.",
  "trackingToastHabitSaveError": "Не удалось сохранить привычку.",
  "trackingToastHabitUpdateError": "Не удалось обновить привычку.",
  "trackingToastPracticeSaveError": "Ошибка при сохранении практики.",
  "trackingToastPracticeUncheckBlocked":
    "Снять отметку практики из календаря пока нельзя — правь в разделе практик.",
  "trackingViewAddAsceticCta": "+ Аскеза",
  "trackingViewAddGoalCta": "+ Цель",
  "trackingViewAddHabitCta": "+ Привычка",
  "trackingViewAddToTrackerBody":
    "Выбери тип сущности, вариант из подборки и сроки — создание здесь же, без других страниц.",
  "trackingViewAddToTrackerTitle": "Добавить на карту",
  "trackingViewAsceticsHintTapDays": "· жми по дням ниже",
  "trackingViewAttentionSectionTitle": "Требует внимания",
  "trackingViewBestSectionTitle": "Лучше всего идёт",
  "trackingViewCompleteGoalConfirm":
    "Отметить цель выполненной? Новые шаги по ней отмечать не получится.",
  "trackingViewContractHereCta": "зафиксировать контракт здесь",
  "trackingViewCreateAsceticCta": "добавить аскезу",
  "trackingViewCreateGoalCta": "создать цель",
  "trackingViewCreateHabitCta": "создать привычку",
  "trackingViewCreateHereCta": "создать здесь",
  "trackingViewEmptyAsceticsLead": "Нет аскез —",
  "trackingViewEmptyGoalsLead": "Нет целей —",
  "trackingViewEmptyHabitsLead": "Нет привычек —",
  "trackingViewFlowTodayEyebrow": "Flow сегодня",
  "trackingViewFreeSoftLimitHint":
    "Для FREE рекомендуем до {{goals}} цели, {{habits}} привычек и {{ascetics}} аскезы — так проще удержать ритм.",
  "trackingViewGoalCompletedSuffix": " · завершена",
  "trackingViewGoalNameAriaLabel": "Название цели",
  "trackingViewGoalStatusPrefix": "Статус:",
  "trackingViewHabitNameAriaLabel": "Название привычки",
  "trackingViewHabitPauseCta": "пауза",
  "trackingViewHabitPausedSuffix": " (на паузе)",
  "trackingViewHabitResumeCta": "включить",
  "trackingViewLimitsHint":
    "Слишком много активного — удержать будет сложно. Подумай, что поставить на паузу.",
  "trackingViewLast30DaysLegend": "Последние 30 дней · ● выполнено · ○ нет · ⚠ срыв / нарушение",
  "trackingViewMarkTodayPromptAfterDate": "— отметь сегодня по каждой сущности.",
  "trackingViewNoActiveItemsLead": "Нет активных —",
  "trackingViewOpenTodayLink": "Открыть «Сегодня»",
  "trackingViewPracticeAggregatedFootnote":
    "Отметки по отдельным практикам из каталога попадают в эту линию автоматически.",
  "trackingViewPracticeAggregatedIntro":
    "Одна агрегированная линия: всё, что отмечено как практика за день. Детали — в разделе практик.",
  "trackingViewRenameTitleLink": "название",
  "trackingViewSystemPracticeToday": "Системная практика сегодня",
  "trackingViewTodayLinkHint":
    "После отметок сущности попадают в «Сегодня» как шаги дня (связка onTodayActionComplete — на стороне Today).",
  "trackingViewWizardFromTypeStep": "Мастер (с шага типа)",
  "weekdayFallback": [
    "Пн",
    "Вт",
    "Ср",
    "Чт",
    "Пт",
    "Сб",
    "Вс"
  ],
  "weeklyPulseEmpty": "Когда накопится несколько дней, здесь появится нативная карта недели по энергии, балансу и фокусу.",
  "weeklyPulseTitle": "Пульс недели",
  "yourGoals": "Твои цели"
} as const;
export const FLOW_TRACKER_CHROME_EN = {
  "affirmationsCatalogEmpty": "Catalog didn’t load or is empty. Next: a native catalog screen.",
  "affirmationsCatalogCountEn": "{{n}} item",
  "affirmationsCatalogCountEnPlural": "{{n}} items",
  "affirmationsCatalogCountRu1": "{{n}} позиция",
  "affirmationsCatalogCountRu24": "{{n}} позиции",
  "affirmationsCatalogCountRuMany": "{{n}} позиций",
  "affirmationsCatalogSectionTitle": "Catalog",
  "affirmationsCtaMoveToday": "Move to Today",
  "affirmationsCtaOpenPractices": "Open practices",
  "affirmationsCtaOpenToday": "Open Today",
  "affirmationsCtaOpenTracker": "Open map",
  "affirmationsCtaSignInToday": "Sign in to open Today",
  "affirmationsCtaSignInUse": "Sign in to use",
  "affirmationsDefaultTitleAffirmation": "Affirmation",
  "affirmationsDefaultTitleMantra": "Mantra",
  "affirmationsEmptyFilterHint":
    "Nothing matches yet. Try loosening filters or broadening your search.",
  "affirmationsFeaturedSectionTitle": "You might resonate with",
  "affirmationsFocusCalmHint": "Ground yourself, exhale, stay contained.",
  "affirmationsFocusCalmTitle": "Calm",
  "affirmationsFocusGrowthHint": "Growth, courage, moving forward.",
  "affirmationsFocusGrowthTitle": "Growth",
  "affirmationsFocusLoveHint": "Contact, closeness, openness, trust.",
  "affirmationsFocusLoveTitle": "Relationships",
  "affirmationsFocusMoneyHint": "Stability, abundance, material footing.",
  "affirmationsFocusMoneyTitle": "Money",
  "affirmationsFocusSupportHint": "A gentle inner voice and recovery.",
  "affirmationsFocusSupportTitle": "Support",
  "affirmationsFocusWorkHint": "Role, execution, decisions, action.",
  "affirmationsFocusWorkTitle": "Work",
  "affirmationsFocusAllHint": "The full library of phrases and anchors.",
  "affirmationsFocusAllTitle": "All themes",
  "affirmationsKindLabelAffirmation": "Affirmation",
  "affirmationsKindLabelMantra": "Mantra",
  "affirmationsKindFilterAffirmation": "Affirmations",
  "affirmationsKindFilterAll": "All",
  "affirmationsKindFilterMantra": "Mantras",
  "affirmationsLibraryLinkAllTrackers": "All maps",
  "affirmationsLibraryLoadError": "Couldn’t load the library.",
  "affirmationsLibraryPageEyebrow": "Library",
  "affirmationsLibraryPageLead":
    "Short phrases and anchor formulas to steady yourself, hold a state, move through tension, or gently lock in a new inner move.",
  "affirmationsLibraryPageTitle": "Affirmations & mantras library",
  "affirmationsLibraryLinkTracker": "Affirmations map",
  "affirmationsMantraPronunciationPrefix": "Pronunciation: {{text}}",
  "affirmationsPersonalBadge": "Personal",
  "affirmationsPersonalCta": "Suggest 3 lines",
  "affirmationsPersonalEmptyHint": "More lines for your theme will show up here.",
  "affirmationsPersonalGenerating": "Gathering…",
  "affirmationsPersonalSectionBody":
    "Want more than the library? Pull a few fresh lines for the theme you picked.",
  "affirmationsPersonalSectionTitle": "Personal lines",
  "affirmationsSearchPlaceholder": "Search by word, state, theme, or meaning…",
  "affirmationsTrackerBackToAllTrackers": "← All maps",
  "affirmationsTrackerBackToCatalog": "← Affirmations catalog",
  "affirmationsTrackerEntryNotUsed": "○ Not used",
  "affirmationsTrackerEntryStateLabel": "State:",
  "affirmationsTrackerEntryUsed": "✓ Used",
  "affirmationsTrackerLoginPrompt": "Sign in to open the affirmations map.",
  "affirmationsTrackerNewEntryTitle": "New entry",
  "affirmationsTrackerNoEntriesForDate": "No entries for this date",
  "affirmationsTrackerNoteLabel": "Note (optional)",
  "affirmationsTrackerNotePlaceholder": "Short note…",
  "affirmationsTrackerPageLead":
    "Short phrases to anchor a state. Pick one affirmation for the day and log that you used it.",
  "affirmationsTrackerScaleLabel": "State scale (1–5)",
  "affirmationsTrackerSelectLabel": "Affirmation (short line)",
  "affirmationsTrackerSelectPlaceholder": "Choose an affirmation",
  "affirmationsTrackerStateLabel": "State (1–2 words)",
  "affirmationsTrackerStatePlaceholder": "e.g. calm, focused",
  "affirmationsTrackerToastPickAffirmation": "Choose an affirmation",
  "affirmationsTrackerUsedLabel": "Used",
  "affirmationsSyncNote": "Same logging as on the website.",
  "affirmationsTitle": "Affirmations",
  "actionCancel": "Cancel",
  "actionSave": "Save",
  "asceticCatalogEmpty": "Ascetic catalog is empty or unavailable.",
  "asceticDurationPicker": "Duration",
  "asceticDurationSection": "Duration",
  "asceticFallbackTitle": "Ascetic",
  "asceticLoadingCatalog": "Loading catalog…",
  "asceticNavTitle": "Ascetic",
  "asceticPracticeSection": "Practice",
  "asceticsEmpty": "No active ascetics to log. Create a contract from Today: Build day → emotions chip.",
  "asceticsSyncNote": "Same day log as on the website.",
  "asceticsTitle": "Ascetics",
  "balance": "Balance",
  "calendarFailed": "Calendar didn’t load",
  "close": "Close",
  "completeGoal": "Complete",
  "connectionHeader": "Connection",
  "create": "Create",
  "createContract": "Create contract",
  "dayTracker": "Day flow",
  "diaryEasierPlaceholder": "1–2 sentences about what felt easier…",
  "diaryEasierPrompt": "What went smoother than expected",
  "diaryEasierTitle": "What felt easier",
  "diaryHardestPlaceholder": "1–2 sentences about where it was hardest…",
  "diaryHardestPrompt": "Where the day started to slip",
  "diaryHardestTitle": "Where it was hardest",
  "diaryIntro": "No drama—what you noticed, what was harder, what felt easier.",
  "diaryNoticedPlaceholder": "1–2 sentences about what you noticed…",
  "diaryNoticedPrompt": "1–2 sentences on the main observation",
  "diaryNoticedTitle": "What you noticed",
  "diaryTitle": "Observation journal",
  "done": "Done",
  "energy": "Energy",
  "focus": "Focus",
  "generateInsight": "Generate insight",
  "generatingInsight": "Generating insight",
  "insightsGenerateErrorFallback": "Couldn’t generate the insight",
  "insightsGeneratingShort": "Generating…",
  "goalLimitReached": "Already 3 goals for this period—finish one or switch period.",
  "goalQuickPeriodNote": "Period follows the day selected in Flow calendar—same as the site.",
  "goalSheetTitle": "Goal",
  "goalsNavTitle": "Goals",
  "goalsPickDateHint": "Pick a date on the Calendar tab, then log a goal step for that day.",
  "habitCadence": "Cadence",
  "habitCategory": "Category (same as web)",
  "habitDaily": "Every day",
  "habitIdeas": "Ideas",
  "habitSheetTitle": "Habit",
  "habitWeekly": "A few times a week",
  "habitsEmpty": "No active habits yet—add one below.",
  "habitsMapAddCreating": "Creating…",
  "habitsMapAddCta": "Add habit",
  "habitsMapAddSectionTitle": "Add a habit",
  "habitsMapCategoryPlaceholder": "Category: body / focus / mind",
  "habitsMapCheckErrorFallback": "Couldn’t log the habit",
  "habitsMapCreateErrorFallback": "Couldn’t create the habit",
  "habitsMapEmptyList": "No habits yet—create your first one above.",
  "habitsMapEyebrow": "Habit map",
  "habitsMapHeroBody":
    "Habits don’t compete with ascetics or practices here. It’s a separate discipline layer—repeatable actions, a soft rhythm strip, and a clear summary.",
  "habitsMapHeroTitle": "A habit map without the noise",
  "habitsMapHowToReadLine1": "Each habit shows its last 28 days as a soft heatmap strip.",
  "habitsMapHowToReadLine2":
    "Logging today isn’t about a checkbox—it shows which actions actually carry your day.",
  "habitsMapHowToReadTitle": "How to read the map",
  "habitsMapLinkCalendar": "Open calendar",
  "habitsMapLinkToday": "To Today",
  "habitsMapLinkTrackingHub": "My maps",
  "habitsMapLoadErrorFallback": "Couldn’t load the habit map",
  "habitsMapLoginLead": "Sign in to shape your rhythm and see your story take shape—no spreadsheets or percentages.",
  "habitsMapMarkedToday": "Logged",
  "habitsMapMarkToday": "Log today",
  "habitsMapNamePlaceholder": "e.g. 10 minutes breathing",
  "habitsMapNoCategory": "no category",
  "habitsMapPageTitle": "Habit map",
  "habitsMapStatsCompact": "{{streak}} days marked on the map",
  "habitsMapStatsPending": "Your story is just beginning",
  "habitsMapStrongestRhythm": "Strongest rhythm now: {{name}}, streak {{days}} d",
  "habitsMapStrongestRhythmEmpty": "After your first check-ins, the steadiest rhythm shows here.",
  "habitsMapSummary30Empty": "Summary appears after the first check-ins.",
  "habitsMapSummary30Title": "30-day summary",
  "habitsMapSummaryStreakLabel": "Streak:",
  "habitsMapTodayProgress": "{{done}} of {{total}} habits logged today",
  "habitsMapTodaySnapshotEyebrow": "Today’s snapshot",
  "habitsSyncNote": "Entries for the selected day match the website.",
  "habitsTitle": "Habits",
  "heatmapDrillAsceticsLinePrefix": "Ascetics (held):",
  "heatmapDrillDayEyebrow": "Day",
  "heatmapDrillGoalsLinePrefix": "Goals:",
  "heatmapDrillHabitsLinePrefix": "Habits:",
  "heatmapDrillPracticeDone": "done",
  "heatmapDrillPracticeLabel": "Practice:",
  "heatmapDrillPracticeNo": "no",
  "heatmapDrillTotalsPrefix": "On the map:",
  "heatmapDrillDayCaptionEmptyTracks": "No active tracks—add a goal, habit, or ascetic.",
  "heatmapDrillDayCaptionGoalsNoStep": "No goal step that day—try one concrete step on a chosen goal.",
  "heatmapDrillDayCaptionPartialDay": "Partly closed—you can still see where to push.",
  "heatmapDrillDayCaptionQuietDay": "Quiet day—almost no movement on tracks.",
  "heatmapDrillDayCaptionStrongDay": "Dense day—solid footing on tracks.",
  "heatmapEntityPickHint": "Pick an entity from the list—or the view stays aggregated by type.",
  "heatmapEntityPickPlaceholder": "Choose…",
  "heatmapUnderMapInsightAllFreeGaps": "There are gaps in the grid—that’s fine if you notice them.",
  "heatmapUnderMapInsightAllFreeSteady": "Overall rhythm looks steady for the selected filter.",
  "heatmapUnderMapInsightAllPremiumReadable": "The month pattern reads—you can see where density builds.",
  "heatmapUnderMapInsightAllPremiumStutter": "You hold for a few days, then drop—no steady rhythm for the whole month.",
  "heatmapUnderMapInsightAllProSteady": "Relatively smooth—few sharp drops.",
  "heatmapUnderMapInsightAllProVolatile": "Uneven rhythm: dense days alternate with empty ones.",
  "heatmapUnderMapInsightAsceticsFreeGaps": "Ascetics have days without holding the line.",
  "heatmapUnderMapInsightAsceticsFreeSteady": "Ascetics look denser.",
  "heatmapUnderMapInsightAsceticsPremium": "If a rich stretch is followed by a sharp drop—the rule may be too harsh.",
  "heatmapUnderMapInsightAsceticsPro": "Slips show up as empty or very light cells in a row.",
  "heatmapUnderMapInsightGoalsFreeGaps": "Goals have days with no step.",
  "heatmapUnderMapInsightGoalsFreeSteady": "Goal movement is more visible.",
  "heatmapUnderMapInsightGoalsPremium": "Goals aren’t moving daily—simplify to one step a day.",
  "heatmapUnderMapInsightGoalsPro": "Goals without daily steps make a “patchy” grid.",
  "heatmapUnderMapInsightHabitsFreeGaps": "Habits have lighter days.",
  "heatmapUnderMapInsightHabitsFreeSteady": "Habits look more stable.",
  "heatmapUnderMapInsightHabitsPremium": "Behavior layer: weekends or end of week are often lighter—check triggers.",
  "heatmapUnderMapInsightHabitsPro": "Habits may not be locked in—watch for “holey” weeks.",
  "heatmapUnderMapInsightPracticesFreeGaps": "System practices aren’t closed every day.",
  "heatmapUnderMapInsightPracticesFreeSteady": "Practices are logged more often.",
  "heatmapUnderMapInsightPracticesPremium": "Compare with ALL: if practices are steady but ALL is patchy—focus goals and habits.",
  "heatmapUnderMapInsightPracticesPro": "One practice per day—the grid shows yes/no discipline.",
  "heatmapFilterGoalsRowTitle": "Goals (empty = all active)",
  "heatmapInsightPrefix": "Insight",
  "heatmapJumpToCurrentMonth": "This month",
  "heatmapLegendEntityDone": "done",
  "heatmapLegendEntityMiss": "none",
  "heatmapLegendIntensity0": "quieter",
  "heatmapLegendIntensityHigh": "brighter",
  "heatmapLegendIntensityLow": "lighter",
  "heatmapLegendIntensityMid": "steady",
  "heatmapLegendNoData": "no data",
  "heatmapMapExplainer": "One day, one cell. Color shows how dense the day was for the selected line. Gray means no data or a future day. No numbers inside cells.",
  "heatmapModeAll": "ALL",
  "heatmapNextMonthA11y": "Next month",
  "heatmapPrevMonthA11y": "Previous month",
  "heatmapRowModeAggregate": "Aggregate (share)",
  "heatmapRowModeLabel": "Row mode:",
  "heatmapRowModeOneEntity": "One entity",
  "heatmapSelectAllShort": "all",
  "heatmapUnderMapEyebrowPrefix": "Under the map",
  "horizonPicker": "Horizon",
  "insightsEmpty": "No insights for this date yet. Add 1–2 entries, then tap Generate insight.",
  "insightsIntro": "Built from calendar entries and journal for the selected day.",
  "insightsTitle": "Auto insights",
  "trackingDiaryEasierFieldLabel": "What felt easier than expected",
  "trackingDiaryEntryFormTitle": "Observation entry",
  "trackingDiaryFillAtLeastOne": "Fill in at least one field",
  "trackingDiaryHardestFieldLabel": "Where it was hardest",
  "trackingDiaryLoginPrompt": "Sign in to use the observation journal",
  "trackingDiaryNoticedFieldLabel": "What I noticed",
  "trackingDiaryPageIntro":
    "Reflection, not analysis—what you noticed, what was hardest, what felt easier. No conclusions, no “why”—just observation.",
  "trackingDiaryReadoutEasier": "What felt easier:",
  "trackingDiaryReadoutHardest": "Where it was hardest:",
  "trackingDiaryReadoutNoticed": "What you noticed:",
  "trackingDiarySaveError": "Couldn’t save the entry",
  "trackingDiaryEntriesHeading": "Entries for {{date}}",
  "trackingFormDateLabel": "Date",
  "trackingInsightConfidenceHigh": "High confidence",
  "trackingInsightConfidenceLow": "Low confidence",
  "trackingInsightConfidenceMedium": "Medium confidence",
  "trackingInsightDataAvgMood": "Mood tone these days:",
  "trackingInsightDataClearDecisions": "Clear decisions:",
  "trackingInsightDataDaysReviewed": "Days in the window:",
  "trackingInsightDataDominantFocus": "Dominant focus:",
  "trackingInsightDataEntries": "Entries:",
  "trackingInsightDataGatheredDays": "Gathered days:",
  "trackingInsightDataRepeatCount": "Repeats:",
  "trackingInsightDataTotalCountSuffix": "{{n}} total",
  "trackingInsightDataUngatheredDays": "Ungathered days:",
  "trackingInsightDataUnclearDecisions": "Unclear decisions:",
  "trackingInsightDataWeekendEntries": "Weekend share:",
  "trackingInsightTypeCorrelation": "Correlation",
  "trackingInsightTypePattern": "Pattern",
  "trackingInsightTypeShift": "Shift",
  "trackingInsightTypeSignalClarity": "Decision clarity",
  "trackingInsightTypeSignalClosure": "Day closure",
  "trackingInsightTypeSignalFocus": "Recurring focus",
  "trackingInsightTypeStreak": "Streak",
  "trackingInsightTypeWeekendPattern": "Weekend pattern",
  "trackingInsightsEmptyHint": "Tap “Generate insight” and add 1–2 check-ins for the day.",
  "trackingInsightsEmptyTitle": "No insights for this date.",
  "trackingInsightsLoginPrompt": "Sign in to see automatic insights",
  "trackingInsightsPageLead": "Short observations for the day and a practical next step.",
  "trackingInsightsPageTitle": "Automatic insights",
  "loadingBootstrap": "Loading calendar and maps...",
  "logPractice": "Log practice",
  "markStep": "Log step",
  "monthMapTitle": "Month map",
  "monthStatsTitle": "This month in numbers",
  "monthSubtitle": "Pick a day and log goals, habits, and practices.",
  "nameFieldPlaceholder": "Name",
  "navFlow": "Flow",
  "newGoal": "New goal",
  "newHabit": "New habit",
  "noGoalsYet": "No goals yet—create one above.",
  "noMarksDay": "No entries for this day yet.",
  "openCalendarForDay": "Open calendar for day entries",
  "openGoals": "Open goals",
  "pickDayOnMap": "Pick a day on the month map.",
  "practiceDoneLabel": "Logged for this day",
  "practiceHint": "Quick log like on the website. You can’t remove it here—only in Practices.",
  "practiceTitle": "Practice",
  "reopenGoal": "Reopen",
  "retry": "Retry",
  "rhythmEncouragementFallback": "Your week rhythm shows in the days you’ve logged.",
  "saveDiary": "Save entry",
  "saveDiarySaving": "Saving…",
  "savedForDay": "Saved for this day",
  "selectedDay": "Selected day",
  "statFullCheckins": "Full check-ins",
  "statGoalDays": "Days with goals",
  "statHabitDays": "Days with habits",
  "stepsForDay": "Steps for this day",
  "streaksNow": "Streaks",
  "summaryEasier": "Easier than expected",
  "summaryHardest": "Hardest",
  "summaryNoticed": "Noticed",
  "syncIssueTitle": "Sync issue",
  "trackerAlertTitle": "Maps",
  "trackingCalendarEmptyState": "No calendar data.",
  "trackingCalendarLoginPrompt": "Sign in to open your maps.",
  "trackingCalendarPageEyebrow": "Maps",
  "trackingCalendarPageIntro": "See how goals, habits, and practices add up day by day. One screen—the full picture of your rhythm.",
  "trackingCalendarPageTitle": "Flow: rhythm and actions",
  "trackingCategoryAsceticEmpty": "no ascetics",
  "trackingCategoryAsceticMixed": "slips, but the track is alive",
  "trackingCategoryAsceticStrong": "you’re keeping the rules",
  "trackingCategoryAsceticWeak": "many stops or breaks",
  "trackingCategoryGoalEmpty": "no goals yet",
  "trackingCategoryGoalMixed": "movement, but not on all",
  "trackingCategoryGoalOverloaded": "too many goals for a steady rhythm",
  "trackingCategoryGoalStrong": "goals are moving",
  "trackingCategoryGoalWeak": "a lot of stagnation on goals",
  "trackingCategoryHabitEmpty": "no habits",
  "trackingCategoryHabitMixed": "some hold, some drift",
  "trackingCategoryHabitStrong": "most are holding",
  "trackingCategoryHabitWeak": "many dropped or weak lines",
  "trackingCategoryPracticeActive": "you’re doing what’s suggested",
  "trackingCategoryPracticeEmpty": "practices not connected",
  "trackingCategoryPracticeIgnored": "system practices are ignored",
  "trackingCategoryPracticeNeutral": "you do them sometimes",
  "trackingCatSummaryAsceticsCounts": "{{total}} active · {{holding}} holding · {{broken}} slipped",
  "trackingCatSummaryAsceticsZero": "0 active",
  "trackingCatSummaryGoalsCounts": "{{total}} active · {{inProgress}} in progress · {{stalled}} stalled",
  "trackingCatSummaryGoalsZero": "0 active",
  "trackingCatSummaryHabitsCounts": "{{total}} active · {{holding}} holding · {{unstable}} unstable",
  "trackingCatSummaryHabitsZero": "0 active",
  "trackingCatSummaryPracticesActive": "in progress",
  "trackingCatSummaryPracticesEmpty": "system suggests practices",
  "trackingCatSummaryPracticesIgnored": "ignored",
  "trackingCatSummaryPracticesNeutral": "sometimes",
  "trackingCatSummaryPracticesPrefix": "system suggests 1 · ",
  "trackingAttentionAsceticBreaksLine": "has slips",
  "trackingAttentionAsceticFailedLine": "{{count}} slips (7-day window)",
  "trackingAttentionGoalStalledLine": "stalled {{days}} d",
  "trackingAttentionHabitDroppedLine": "dropped · no check-ins {{days}} d",
  "trackingAttentionUnstableShort": "unstable",
  "trackingBestAsceticHoldLine": "holding {{n}} d",
  "trackingBestGoalSteps5dLine": "{{n}} steps in 5 days",
  "trackingBestHabitStreakLine": "{{n}} days in a row",
  "trackingEntityWizardAsceticCatalogLoadError": "Couldn’t load the ascetics catalog",
  "trackingEntityWizardAsceticCreatedSuccess": "Ascetic contract saved",
  "trackingEntityWizardAsceticDirectionLabel": "Direction",
  "trackingEntityWizardAsceticDurationContractLabel": "Contract length",
  "trackingEntityWizardAsceticDurationDays14": "14 days",
  "trackingEntityWizardAsceticDurationDays21": "21 days",
  "trackingEntityWizardAsceticDurationDays30": "30 days",
  "trackingEntityWizardAsceticDurationDays7": "7 days",
  "trackingEntityWizardAsceticDurationOpen": "Open-ended",
  "trackingEntityWizardAsceticEmptyCategoryHint": "Nothing in this category—pick “All”.",
  "trackingEntityWizardAsceticEndOpenHint": "No end date—this is an open contract",
  "trackingEntityWizardAsceticEndUntil": "Through {{date}} inclusive",
  "trackingEntityWizardAsceticKindDesc": "A mindful limit with a contract",
  "trackingEntityWizardAsceticKindTitle": "Ascetic",
  "trackingEntityWizardBack": "Back",
  "trackingEntityWizardCategoryLabel": "Category",
  "trackingEntityWizardCreateCta": "Create",
  "trackingEntityWizardCustomVariantLabel": "Your wording",
  "trackingEntityWizardGoalCreatedSuccess": "Goal added",
  "trackingEntityWizardGoalKindDesc": "Week or month focus with steps on the calendar",
  "trackingEntityWizardGoalKindTitle": "Goal",
  "trackingEntityWizardHabitCreatedSuccess": "Habit created",
  "trackingEntityWizardHabitKindDesc": "A repeating action with a day/week rhythm",
  "trackingEntityWizardHabitKindTitle": "Habit",
  "trackingEntityWizardHabitWeeklyTargetLabel": "Times per week (target)",
  "trackingEntityWizardHabitWeeklyTimes": "{{n}}×",
  "trackingEntityWizardLoadingAsceticCatalog": "Loading catalog…",
  "trackingEntityWizardNeedTitleOrPick": "Enter a name or pick a suggestion",
  "trackingEntityWizardNextTimings": "Next: timing",
  "trackingEntityWizardPeriodLabel": "Period",
  "trackingEntityWizardPlaceholderCustomTitle": "Short wording for your goal or habit",
  "trackingEntityWizardRhythmLabel": "Rhythm",
  "trackingEntityWizardSaveFailed": "Couldn’t save",
  "trackingEntityWizardSaving": "Saving…",
  "trackingEntityWizardStartLabel": "Start",
  "trackingEntityWizardStepPickKind": "What are you adding?",
  "trackingEntityWizardStepPickVariant": "Pick a variant",
  "trackingEntityWizardStepProgress": "Step {{step}} of 3",
  "trackingEntityWizardStepTimingsCreate": "Timing and create",
  "trackingEntityWizardMonthFrom": "Month (from {{date}})",
  "trackingEntityWizardWeekFrom": "Week (from {{date}})",
  "trackingFooter": "Your rhythm story gathers here.",
  "trackingMarkTodayAfterSave": "Today counted",
  "trackingMarkTodayFab": "Mark today",
  "trackingMarkTodayFabEmpty": "Log your first day",
  "trackingMarkTodayModalTitle": "Today",
  "trackingProgressCardAffirmationsDesc": "A dedicated flow for affirmations.",
  "trackingProgressCardAffirmationsTitle": "Affirmations map",
  "trackingProgressCardAsceticClassicDesc": "Alternate screen for ascetic check-ins only—if you prefer the classic flow.",
  "trackingProgressCardAsceticClassicTitle": "Ascetics map (classic)",
  "trackingProgressCardHabitsListDesc": "Broader overview and history—creation matches the calendar wizard.",
  "trackingProgressCardHabitsListTitle": "Habit map",
  "trackingProgressCardMainCalendarDesc": "Main hub: month map, goals, habits, ascetics, and practices. Create goals, habits, and ascetic contracts right here—no extra hops.",
  "trackingProgressCardMainCalendarTitle": "Rhythm map",
  "trackingProgressCardQuickAsceticDesc": "Pick from the catalog and set the contract length.",
  "trackingProgressCardQuickAsceticTitle": "Quick: new ascetic",
  "trackingProgressCardQuickGoalDesc": "Opens the calendar with the goal creation wizard.",
  "trackingProgressCardQuickGoalTitle": "Quick: new goal",
  "trackingProgressCardQuickHabitDesc": "Habit wizard with template picks.",
  "trackingProgressCardQuickHabitTitle": "Quick: new habit",
  "trackingProgressFooterAffirmationsLibrary": "Affirmations & mantras library",
  "trackingProgressFooterAsceticCatalog": "Ascetics catalog",
  "trackingProgressHubEyebrow": "History",
  "trackingProgressHubIntro": "Life maps in one place: month rhythm, habits, ascetics, and affirmations. Each day in Today adds a point—the pattern grows on its own.",
  "trackingProgressHubLoginBody": "Sign in to open your rhythm, habit, ascetic, and affirmation maps.",
  "trackingProgressHubLoginCta": "Sign in",
  "trackingProgressHubLoginTitle": "My maps",
  "trackingProgressHubTitle": "My maps",
  "trackingScreenHeroDroppedSub": "Most tracks aren’t moving—return to a simple step.",
  "trackingScreenHeroDroppedTitle": "Many lines without support",
  "trackingScreenHeroEmptySub": "Add a goal, habit, or ascetic—then you’ll see the full picture.",
  "trackingScreenHeroEmptyTitle": "Start with one line",
  "trackingScreenHeroInFlowSub": "You’re holding what you committed to.",
  "trackingScreenHeroInFlowTitle": "You’re in rhythm",
  "trackingScreenHeroOverloadedSub": "Too many active tracks; holding everything is hard.",
  "trackingScreenHeroOverloadedTitle": "You’re overloaded",
  "trackingScreenHeroUnstableSub": "Some lines hold, others have slipped.",
  "trackingScreenHeroUnstableTitle": "You’re losing the rhythm",
  "trackingStatusAsceticBreaks": "there are slips",
  "trackingStatusAsceticFailed": "slips in a row",
  "trackingStatusAsceticHolding": "holding on",
  "trackingStatusAsceticStopped": "stopped",
  "trackingStatusGoalActiveProgress": "in progress",
  "trackingStatusGoalCompleted": "completed",
  "trackingStatusGoalStalled": "stalled",
  "trackingStatusGoalUnstable": "unstable",
  "trackingStatusHabitActive": "holding",
  "trackingStatusHabitDropped": "dropped",
  "trackingStatusHabitUnstable": "unstable",
  "trackingToastAsceticLogError": "Couldn’t save ascetic check-in.",
  "trackingToastGoalCompleteError": "Couldn’t complete the goal.",
  "trackingToastGoalCompleteSuccess": "Goal marked complete.",
  "trackingToastGoalNameEmpty": "Title can’t be empty.",
  "trackingToastGoalRenameError": "Couldn’t save the title.",
  "trackingToastGoalRenameSuccess": "Goal title updated.",
  "trackingToastGoalStepDuplicate": "This goal already has a step logged for that day.",
  "trackingToastGoalStepError": "Couldn’t log the goal step.",
  "trackingToastHabitActive": "Habit is active again.",
  "trackingToastHabitPaused": "Habit paused.",
  "trackingToastHabitRenameSuccess": "Habit name updated.",
  "trackingToastHabitSaveError": "Couldn’t save habit.",
  "trackingToastHabitUpdateError": "Couldn’t update habit.",
  "trackingToastPracticeSaveError": "Error saving practice.",
  "trackingToastPracticeUncheckBlocked":
    "You can’t remove a practice mark from the calendar yet—change it in Practices.",
  "trackingViewAddAsceticCta": "+ Ascetic",
  "trackingViewAddGoalCta": "+ Goal",
  "trackingViewAddHabitCta": "+ Habit",
  "trackingViewAddToTrackerBody":
    "Pick a type, a suggestion, and timing—everything is created here, no extra pages.",
  "trackingViewAddToTrackerTitle": "Add to map",
  "trackingViewAsceticsHintTapDays": "· tap the days below",
  "trackingViewAttentionSectionTitle": "Needs attention",
  "trackingViewBestSectionTitle": "Going best",
  "trackingViewCompleteGoalConfirm":
    "Mark this goal complete? You won’t be able to log new steps on it.",
  "trackingViewContractHereCta": "set up a contract here",
  "trackingViewCreateAsceticCta": "add an ascetic",
  "trackingViewCreateGoalCta": "create a goal",
  "trackingViewCreateHabitCta": "create a habit",
  "trackingViewCreateHereCta": "create here",
  "trackingViewEmptyAsceticsLead": "No ascetics —",
  "trackingViewEmptyGoalsLead": "No goals —",
  "trackingViewEmptyHabitsLead": "No habits —",
  "trackingViewFlowTodayEyebrow": "Flow today",
  "trackingViewFreeSoftLimitHint":
    "On FREE we recommend up to {{goals}} goal, {{habits}} habits, and {{ascetics}} ascetics—it’s easier to keep rhythm.",
  "trackingViewGoalCompletedSuffix": " · completed",
  "trackingViewGoalNameAriaLabel": "Goal title",
  "trackingViewGoalStatusPrefix": "Status:",
  "trackingViewHabitNameAriaLabel": "Habit name",
  "trackingViewHabitPauseCta": "pause",
  "trackingViewHabitPausedSuffix": " (paused)",
  "trackingViewHabitResumeCta": "resume",
  "trackingViewLimitsHint": "Too much active at once—hard to sustain. Consider pausing something.",
  "trackingViewLast30DaysLegend": "Last 30 days · ● done · ○ none · ⚠ slip / break",
  "trackingViewMarkTodayPromptAfterDate": "— log today for each entity.",
  "trackingViewNoActiveItemsLead": "None active —",
  "trackingViewOpenTodayLink": "Open Today",
  "trackingViewPracticeAggregatedFootnote":
    "Marks from individual catalog practices roll into this line automatically.",
  "trackingViewPracticeAggregatedIntro":
    "One aggregated line: everything logged as practice for the day. Details live in Practices.",
  "trackingViewRenameTitleLink": "rename",
  "trackingViewSystemPracticeToday": "System practice today",
  "trackingViewTodayLinkHint":
    "After check-ins, entities show up in Today as day steps (onTodayActionComplete wiring lives on the Today side).",
  "trackingViewWizardFromTypeStep": "Wizard (from type step)",
  "weekdayFallback": [
    "Mon",
    "Tue",
    "Wed",
    "Thu",
    "Fri",
    "Sat",
    "Sun"
  ],
  "weeklyPulseEmpty": "After a few days, a native week map for energy, balance, and focus appears here.",
  "weeklyPulseTitle": "Weekly pulse",
  "yourGoals": "Your goals"
} as const;

export const PRACTICES_EXPERIENCE_CHROME_RU = {
  "a11yHistory": "История практик",
  "a11yRefresh": "Обновить",
  "affirmationsApi": "Аффирмации (API практик)",
  "affirmationsSubtitle": "До 25 аффирмаций из подборки практик",
  "asceticsBlock": "Аскезы",
  "asceticsSubtitle": "Практики сдержанности из каталога",
  "audioSection": "Аудио",
  "byCategory": "По категориям",
  "catalogSection": "Каталог",
  "categoryLabel": "Категория",
  "completedPractices": "Выполненные практики",
  "durationAny": "Любая",
  "durationLong": "10+ мин",
  "durationMedium": "6–10 мин",
  "durationShort": "1–5 мин",
  "emptyFiltered": "Пока нет практик по выбранным фильтрам.",
  "emptyHistoryBody": "Начни выполнять практики с вкладки «Практики», чтобы видеть прогресс здесь.",
  "emptyHistoryTitle": "Пока нет истории",
  "errorPractice403Head": "Доступ к этой практике сейчас недоступен (403).",
  "errorPractice403Tail": "На вкладке «Практики» открой карточку «Лимит на неделю» — там остаток персональных практик на неделю и тариф.",
  "filterAll": "Все",
  "filterCycle": "Цикличные",
  "filterDaily": "Ежедневные",
  "filterMonthly": "Месячные",
  "filterWeekly": "Недельные",
  "filtersTitle": "Фильтры",
  "forYouBadge": "Для тебя",
  "forYouNow": "Сейчас для тебя",
  "hintSection": "Подсказка",
  "historyProgressSubtitle": "Те же данные, что на вебе: `GET /practices/history`, `GET /practices/progress`.",
  "historyProgressTitle": "История и прогресс",
  "howToSection": "Как сделать",
  "interpretationTitle": "Смысл и практика дня",
  "loadingHistory": "Загружаю историю…",
  "loadingPractices": "Загружаю практики…",
  "markComplete": "Отметить выполненной",
  "minutesShort": "мин",
  "nativeHubBody": "Все основные вызовы `/practices/*` подключены; оформление экранов можно донастроить отдельно.",
  "nativeHubTitle": "Нативный хаб",
  "navHistory": "История",
  "navPractices": "Практики",
  "openPractice": "Открыть практику",
  "personalizedLine": "Персональные практики",
  "pickerDuration": "Длительность",
  "pickerPeriodicity": "Периодичность",
  "planLabel": "План",
  "practiceFallbackTitle": "Практика",
  "reflectionSection": "Вопросы для рефлексии",
  "relatedSection": "Связанные практики",
  "remainingLabel": "Осталось",
  "repeatCta": "Повторить",
  "savedToHistory": "Сохранено в истории практик.",
  "saving": "Сохраняю…",
  "sequenceComplete": "Серия завершена — шаги сохранены в истории.",
  "sequenceProgressTitle": "Прогресс по серии",
  "sequencesSubtitle": "Пошаговые недельные треки — те же данные, что `GET /practices/sequences`.",
  "sequencesTitle": "Серии практик",
  "seriesBadge": "Серия",
  "shortAlternatives": "Короткие альтернативы",
  "shortAlternativesSubtitle": "Подбор коротких практик под твой запрос",
  "statBestStreak": "Лучшая серия",
  "statCurrentStreak": "Текущая серия",
  "statPersonalized": "Персонализированных",
  "statTotalDone": "Всего выполнено",
  "statWeeksActive": "Недель активно",
  "statistics": "Статистика",
  "stepsDoneLabel": "Выполнено шагов",
  "stepsSection": "Шаги",
  "toCatalog": "К каталогу практик",
  "unlimitedShort": "без ограничений",
  "weeklyLimitTitle": "Лимит на неделю",
  "practicesCatalogBack": "← Назад",
  "practicesCatalogChooseDirection": "Выбери направление",
  "practicesCatalogDifficultyAdvanced": "Продвинутый",
  "practicesCatalogDifficultyBeginner": "Начинающий",
  "practicesCatalogDifficultyIntermediate": "Средний",
  "practicesCatalogDurationBadgeAny": "Любая",
  "practicesCatalogDurationBadgeLong": "Длинная",
  "practicesCatalogDurationBadgeMedium": "Средняя",
  "practicesCatalogDurationBadgeShort": "Короткая",
  "practicesCatalogDurationPickAnyHint": "Показывать весь каталог",
  "practicesCatalogDurationPickAnyLabel": "Неважно",
  "practicesCatalogDurationPickLongHint": "10+ минут и последовательности",
  "practicesCatalogDurationPickLongLabel": "Длинные",
  "practicesCatalogDurationPickMediumHint": "6–10 минут",
  "practicesCatalogDurationPickMediumLabel": "Средние",
  "practicesCatalogDurationPickShortHint": "1–5 минут",
  "practicesCatalogDurationPickShortLabel": "Короткие",
  "practicesCatalogEmptyFilter": "В этом фильтре нет практик. Попробуй выбрать другой формат.",
  "practicesCatalogFormatLabel": "Формат практики",
  "practicesCatalogGoalPrompt": "Какую цель ты хочешь достичь?",
  "practicesCatalogLoadError": "Не удалось загрузить практики",
  "practicesCatalogLongMorningBody":
    "Если тебе ближе не микро-паузы, а более длинная медитация, ходьба или целая последовательность, теперь это можно явно выбирать прямо в каталоге.",
  "practicesCatalogLongMorningTitle": "Длинные утренние форматы",
  "practicesCatalogMusicBody":
    "Следующий слой для расширения уже очевиден: отдельные медитации и музыка для практики. Сейчас каталог подготовлен так, чтобы этот слой можно было встроить естественно.",
  "practicesCatalogMusicTitle": "Музыка и медитации",
  "practicesCatalogOtherPractices": "Другие практики в этом направлении",
  "practicesCatalogPageSubtitle":
    "Практики для осознанного развития. Выбери цель и направление, и мы подберем формат, который лучше встраивается в твой ритм.",
  "practicesCatalogPageTitle": "Практики",
  "practicesCatalogTodayLabel": "Сегодня",
  "practicesCatalogProgressOf": "из",
  "practicesCatalogCategoriesAria": "Категории практик",
  "practicesCatalogTabAll": "Все",
  "practicesCatalogTabBreath": "Дыхание",
  "practicesCatalogTabMeditation": "Медитации",
  "practicesCatalogTabAffirmation": "Аффirmации",
  "practicesCatalogTabAscetic": "Аскезы",
  "practicesCatalogCategoryBreath": "Дыхание",
  "practicesCatalogCategoryMeditation": "Медитация",
  "practicesCatalogCategoryAffirmation": "Аффirmация",
  "practicesCatalogCategoryAscetic": "Аскеза",
  "practicesCatalogCategoryJournal": "Письмо",
  "practicesCatalogMinutesShort": "мин",
  "practicesCatalogPersonalizedBadge": "Персонально для тебя",
  "practicesCatalogWizardStepsAria": "Шаги подбора практики",
  "practicesRailMyStreak": "Моя серия",
  "practicesRailActiveCount": "Активных практик:",
  "practicesRailBestStreak": "Лучший результат:",
  "practicesRailWeeklyRhythm": "Недельный ритм",
  "practicesRailDaysSuffix": "дней",
  "practicesCatalogPeriodicityBadgeCycle": "Цикличная",
  "practicesCatalogPeriodicityBadgeDaily": "Ежедневная",
  "practicesCatalogPeriodicityBadgeMonthly": "Месячная",
  "practicesCatalogPeriodicityBadgeWeekly": "Недельная",
  "practicesCatalogPersonalizedWhyPrefix": "Почему эта практика:",
  "practicesCatalogPracticeForYou": "Практика для тебя",
  "practicesCatalogStartPractice": "Начать практику",
  "practicesCatalogTimeQuestion": "Сколько времени ты реально готов дать этой практике?",
  "practicesCatalogWizardStepDirection": "Направление",
  "practicesCatalogWizardStepGoal": "Цель",
  "practicesCatalogWizardStepPractice": "Практика",
  "practiceDetailAccessFree": "Бесплатно",
  "practiceDetailAccessSubscription": "По подписке",
  "practiceDetailAudioUnsupported": "Ваш браузер не поддерживает аудио.",
  "practiceDetailAuthOnlyTitle": "Эта практика доступна только для зарегистрированных пользователей",
  "practiceDetailBackLink": "← Вернуться к практикам",
  "practiceDetailBackToPracticesCta": "Вернуться к практикам",
  "practiceDetailCompleteErrorFallback": "Ошибка при отметке практики",
  "practiceDetailCompletedFallbackBody": "Практика завершена.",
  "practiceDetailCompleteStepCta": "Завершить шаг {{n}}",
  "practiceDetailCompletionWorkedPattern": "Ты только что поработал с паттерном",
  "practiceDetailDurationValue": "{{n}} минут",
  "practiceDetailFreeLimitBody": "Зарегистрируйся, чтобы получить доступ ко всем практикам",
  "practiceDetailFreeLimitTitle": "Лимит бесплатных практик исчерпан",
  "practiceDetailHowToTitle": "Как практиковать",
  "practiceDetailJournalFixFeelingCta": "Зафиксировать ощущение →",
  "practiceDetailMarkCompleteCta": "Отметить как выполненное",
  "practiceDetailMarkingShort": "Отмечаю...",
  "practiceDetailMetaAccess": "Доступ",
  "practiceDetailMetaDuration": "Длительность",
  "practiceDetailMetaLevel": "Уровень",
  "practiceDetailNextStepPrefix": "Следующий шаг:",
  "practiceDetailNotFoundTitle": "Практика не найдена",
  "practiceDetailOpenProfileRewardsCta": "Открыть профиль и награды →",
  "practiceDetailPatternExploreCta": "Посмотреть, как это связано с тобой →",
  "practiceDetailReflectionQuestionsTitle": "Вопросы для размышления",
  "practiceDetailSequenceDoneShort": "✨ Серия завершена!",
  "practiceDetailSequenceProgressHeading": "Прогресс по серии",
  "practiceDetailSequenceStepsTitle": "Шаги серии ({{count}} дней)",
  "practiceDetailSignUpCta": "Зарегистрироваться",
  "practiceDetailStepCompleteErrorFallback": "Ошибка при завершении шага",
  "practiceDetailStepDoneToast": "Шаг {{n}} завершен!",
  "practiceDetailStepDurationValue": "{{n}} минут",
  "practiceDetailStepQuestionsLabel": "Вопросы:",
  "practiceDetailTodaysTaskTitle": "Задание на сегодня",
  "practicePatternAxisA1": "Ориентация идентичности",
  "practicePatternAxisA2": "Эмоциональная обработка",
  "practicePatternAxisA3": "Принятие решений",
  "practicePatternAxisA4": "Стабильность и изменения",
  "practicePatternAxisA5": "Ориентация контроля",
  "practicePatternAxisA6": "Реляционная ориентация",
  "practicePatternAxisA7": "Управление энергией",
  "practicesHistoryAuthRequired": "Требуется авторизация",
  "practicesHistoryBrowseCta": "Перейти к практикам",
  "practicesHistoryByCategoryHeading": "Прогресс по категориям",
  "practicesHistoryCategoryAffirmation": "Аффирмация",
  "practicesHistoryCategoryBreathing": "Дыхание",
  "practicesHistoryCategoryEmotions": "Эмоции",
  "practicesHistoryCategoryFocus": "Фокус",
  "practicesHistoryCategoryGratitude": "Благодарность",
  "practicesHistoryCategoryMeditation": "Медитация",
  "practicesHistoryCategoryOther": "Другое",
  "practicesHistoryCategoryReflection": "Рефлексия",
  "practicesHistoryCategoryRitual": "Ритуал",
  "practicesHistoryEmptyBody": "Начните выполнять практики, чтобы отслеживать свой прогресс.",
  "practicesHistoryEmptyTitle": "У вас пока нет истории практик",
  "practicesHistoryErrorTitle": "Ошибка загрузки",
  "practicesHistoryLoadFailed": "Не удалось загрузить данные о практиках",
  "practicesHistoryPageSubtitle": "Отслеживайте свой прогресс и историю выполненных практик",
  "practicesHistoryPersonalizedBadge": "Персонализированная",
  "practicesHistoryPersonalizedShort": "перс.",
  "practicesHistoryProgressStatsHeading": "Статистика прогресса",
  "practicesHistorySectionProgress": "Прогресс",
  "practicesHistorySeriesStepLabel": "Серия: шаг",
  "practicesHistoryUnitDay1": "день",
  "practicesHistoryUnitDayN": "дней",
  "practicesHistoryUnitPractice1": "практика",
  "practicesHistoryUnitPracticeN": "практик"
} as const;
export const PRACTICES_EXPERIENCE_CHROME_EN = {
  "a11yHistory": "Practice history",
  "a11yRefresh": "Refresh",
  "affirmationsApi": "Affirmations (practices API)",
  "affirmationsSubtitle": "Up to 25 affirmations from the practice set",
  "asceticsBlock": "Ascetics",
  "asceticsSubtitle": "Restraint practices from the catalog",
  "audioSection": "Audio",
  "byCategory": "By category",
  "catalogSection": "Catalog",
  "categoryLabel": "Category",
  "completedPractices": "Completed practices",
  "durationAny": "Any",
  "durationLong": "10+ min",
  "durationMedium": "6–10 min",
  "durationShort": "1–5 min",
  "emptyFiltered": "No practices match these filters.",
  "emptyHistoryBody": "Complete practices from the Practices tab to see progress here.",
  "emptyHistoryTitle": "No history yet",
  "errorPractice403Head": "This practice isn’t available right now (403).",
  "errorPractice403Tail": "On the Practices tab, open the Weekly limit card—remaining personalized practices and your plan are there.",
  "filterAll": "All",
  "filterCycle": "Cyclic",
  "filterDaily": "Daily",
  "filterMonthly": "Monthly",
  "filterWeekly": "Weekly",
  "filtersTitle": "Filters",
  "forYouBadge": "For you",
  "forYouNow": "For you now",
  "hintSection": "Hint",
  "historyProgressSubtitle": "Same as web: `GET /practices/history`, `GET /practices/progress`.",
  "historyProgressTitle": "History and progress",
  "howToSection": "How to do it",
  "interpretationTitle": "Meaning and practice of the day",
  "loadingHistory": "Loading history…",
  "loadingPractices": "Loading practices…",
  "markComplete": "Mark complete",
  "minutesShort": "min",
  "nativeHubBody": "Core `/practices/*` calls are wired; UI polish can follow.",
  "nativeHubTitle": "Native hub",
  "navHistory": "History",
  "navPractices": "Practices",
  "openPractice": "Open practice",
  "personalizedLine": "Personalized practices",
  "pickerDuration": "Duration",
  "pickerPeriodicity": "Periodicity",
  "planLabel": "Plan",
  "practiceFallbackTitle": "Practice",
  "reflectionSection": "Reflection prompts",
  "relatedSection": "Related practices",
  "remainingLabel": "Left",
  "repeatCta": "Repeat",
  "savedToHistory": "Saved to practice history.",
  "saving": "Saving…",
  "sequenceComplete": "Sequence complete—steps saved to history.",
  "sequenceProgressTitle": "Sequence progress",
  "sequencesSubtitle": "Weekly step tracks—same data as `GET /practices/sequences`.",
  "sequencesTitle": "Practice sequences",
  "seriesBadge": "Series",
  "shortAlternatives": "Short alternatives",
  "shortAlternativesSubtitle": "Short practices matched to your request",
  "statBestStreak": "Best streak",
  "statCurrentStreak": "Current streak",
  "statPersonalized": "Personalized",
  "statTotalDone": "Total completed",
  "statWeeksActive": "Active weeks",
  "statistics": "Statistics",
  "stepsDoneLabel": "Steps done",
  "stepsSection": "Steps",
  "toCatalog": "Back to catalog",
  "unlimitedShort": "unlimited",
  "weeklyLimitTitle": "Weekly limit",
  "practicesCatalogBack": "← Back",
  "practicesCatalogChooseDirection": "Choose a direction",
  "practicesCatalogDifficultyAdvanced": "Advanced",
  "practicesCatalogDifficultyBeginner": "Beginner",
  "practicesCatalogDifficultyIntermediate": "Intermediate",
  "practicesCatalogDurationBadgeAny": "Any",
  "practicesCatalogDurationBadgeLong": "Long",
  "practicesCatalogDurationBadgeMedium": "Medium",
  "practicesCatalogDurationBadgeShort": "Short",
  "practicesCatalogDurationPickAnyHint": "Show the full catalog",
  "practicesCatalogDurationPickAnyLabel": "No preference",
  "practicesCatalogDurationPickLongHint": "10+ minutes and sequences",
  "practicesCatalogDurationPickLongLabel": "Long",
  "practicesCatalogDurationPickMediumHint": "6–10 minutes",
  "practicesCatalogDurationPickMediumLabel": "Medium",
  "practicesCatalogDurationPickShortHint": "1–5 minutes",
  "practicesCatalogDurationPickShortLabel": "Short",
  "practicesCatalogEmptyFilter": "No practices in this filter. Try another format.",
  "practicesCatalogFormatLabel": "Practice format",
  "practicesCatalogGoalPrompt": "What do you want to work toward?",
  "practicesCatalogLoadError": "Couldn’t load practices",
  "practicesCatalogLongMorningBody":
    "If you prefer more than micro-pauses—longer meditation, walking, or a full sequence—you can choose that explicitly in the catalog.",
  "practicesCatalogLongMorningTitle": "Longer morning formats",
  "practicesCatalogMusicBody":
    "The next layer is clear: dedicated meditations and music for practice. The catalog is structured so that layer can land naturally.",
  "practicesCatalogMusicTitle": "Music and meditations",
  "practicesCatalogOtherPractices": "More practices in this direction",
  "practicesCatalogPageSubtitle":
    "Practices for mindful growth. Pick a goal and direction, and we’ll suggest a format that fits your rhythm.",
  "practicesCatalogPageTitle": "Practices",
  "practicesCatalogTodayLabel": "Today",
  "practicesCatalogProgressOf": "of",
  "practicesCatalogCategoriesAria": "Practice categories",
  "practicesCatalogTabAll": "All",
  "practicesCatalogTabBreath": "Breath",
  "practicesCatalogTabMeditation": "Meditations",
  "practicesCatalogTabAffirmation": "Affirmations",
  "practicesCatalogTabAscetic": "Ascetics",
  "practicesCatalogCategoryBreath": "Breath",
  "practicesCatalogCategoryMeditation": "Meditation",
  "practicesCatalogCategoryAffirmation": "Affirmation",
  "practicesCatalogCategoryAscetic": "Ascetic",
  "practicesCatalogCategoryJournal": "Writing",
  "practicesCatalogMinutesShort": "min",
  "practicesCatalogPersonalizedBadge": "Personalized for you",
  "practicesCatalogWizardStepsAria": "Practice selection steps",
  "practicesRailMyStreak": "My streak",
  "practicesRailActiveCount": "Active practices:",
  "practicesRailBestStreak": "Best streak:",
  "practicesRailWeeklyRhythm": "Weekly rhythm",
  "practicesRailDaysSuffix": "days",
  "practicesCatalogPeriodicityBadgeCycle": "Cyclic",
  "practicesCatalogPeriodicityBadgeDaily": "Daily",
  "practicesCatalogPeriodicityBadgeMonthly": "Monthly",
  "practicesCatalogPeriodicityBadgeWeekly": "Weekly",
  "practicesCatalogPersonalizedWhyPrefix": "Why this practice:",
  "practicesCatalogPracticeForYou": "A practice for you",
  "practicesCatalogStartPractice": "Start practice",
  "practicesCatalogTimeQuestion": "How much time can you honestly give this practice?",
  "practicesCatalogWizardStepDirection": "Direction",
  "practicesCatalogWizardStepGoal": "Goal",
  "practicesCatalogWizardStepPractice": "Practice",
  "practiceDetailAccessFree": "Free",
  "practiceDetailAccessSubscription": "Subscription",
  "practiceDetailAudioUnsupported": "Your browser does not support audio.",
  "practiceDetailAuthOnlyTitle": "This practice is only available for signed-in users",
  "practiceDetailBackLink": "← Back to practices",
  "practiceDetailBackToPracticesCta": "Back to practices",
  "practiceDetailCompleteErrorFallback": "Couldn’t mark the practice complete",
  "practiceDetailCompletedFallbackBody": "Practice completed.",
  "practiceDetailCompleteStepCta": "Complete step {{n}}",
  "practiceDetailCompletionWorkedPattern": "You just worked with the pattern",
  "practiceDetailDurationValue": "{{n}} minutes",
  "practiceDetailFreeLimitBody": "Sign up to access all practices",
  "practiceDetailFreeLimitTitle": "You’ve used your free practices",
  "practiceDetailHowToTitle": "How to practice",
  "practiceDetailJournalFixFeelingCta": "Capture how it felt →",
  "practiceDetailMarkCompleteCta": "Mark as done",
  "practiceDetailMarkingShort": "Marking…",
  "practiceDetailMetaAccess": "Access",
  "practiceDetailMetaDuration": "Duration",
  "practiceDetailMetaLevel": "Level",
  "practiceDetailNextStepPrefix": "Next step:",
  "practiceDetailNotFoundTitle": "Practice not found",
  "practiceDetailOpenProfileRewardsCta": "Open profile and rewards →",
  "practiceDetailPatternExploreCta": "See how this connects to you →",
  "practiceDetailReflectionQuestionsTitle": "Reflection questions",
  "practiceDetailSequenceDoneShort": "✨ Series complete!",
  "practiceDetailSequenceProgressHeading": "Series progress",
  "practiceDetailSequenceStepsTitle": "Series steps ({{count}} days)",
  "practiceDetailSignUpCta": "Sign up",
  "practiceDetailStepCompleteErrorFallback": "Couldn’t complete the step",
  "practiceDetailStepDoneToast": "Step {{n}} complete!",
  "practiceDetailStepDurationValue": "{{n}} minutes",
  "practiceDetailStepQuestionsLabel": "Questions:",
  "practiceDetailTodaysTaskTitle": "Today’s prompt",
  "practicePatternAxisA1": "Identity orientation",
  "practicePatternAxisA2": "Emotional processing",
  "practicePatternAxisA3": "Decision-making",
  "practicePatternAxisA4": "Stability and change",
  "practicePatternAxisA5": "Control orientation",
  "practicePatternAxisA6": "Relational orientation",
  "practicePatternAxisA7": "Energy management",
  "practicesHistoryAuthRequired": "Sign in required",
  "practicesHistoryBrowseCta": "Go to practices",
  "practicesHistoryByCategoryHeading": "Progress by category",
  "practicesHistoryCategoryAffirmation": "Affirmation",
  "practicesHistoryCategoryBreathing": "Breathing",
  "practicesHistoryCategoryEmotions": "Emotions",
  "practicesHistoryCategoryFocus": "Focus",
  "practicesHistoryCategoryGratitude": "Gratitude",
  "practicesHistoryCategoryMeditation": "Meditation",
  "practicesHistoryCategoryOther": "Other",
  "practicesHistoryCategoryReflection": "Reflection",
  "practicesHistoryCategoryRitual": "Ritual",
  "practicesHistoryEmptyBody": "Complete practices to see your progress here.",
  "practicesHistoryEmptyTitle": "No practice history yet",
  "practicesHistoryErrorTitle": "Couldn’t load",
  "practicesHistoryLoadFailed": "Couldn’t load practice data",
  "practicesHistoryPageSubtitle": "Track your progress and completed practice history",
  "practicesHistoryPersonalizedBadge": "Personalized",
  "practicesHistoryPersonalizedShort": "pers.",
  "practicesHistoryProgressStatsHeading": "Progress statistics",
  "practicesHistorySectionProgress": "Progress",
  "practicesHistorySeriesStepLabel": "Series: step",
  "practicesHistoryUnitDay1": "day",
  "practicesHistoryUnitDayN": "days",
  "practicesHistoryUnitPractice1": "practice",
  "practicesHistoryUnitPracticeN": "practices"
} as const;

export type FlowTrackerChromeBundle = typeof FLOW_TRACKER_CHROME_RU | typeof FLOW_TRACKER_CHROME_EN;

export function flowTrackerChromeBundle(locale: FlowPracticesChromeLocale): FlowTrackerChromeBundle {
  return locale === "ru" ? FLOW_TRACKER_CHROME_RU : FLOW_TRACKER_CHROME_EN;
}

export type PracticesExperienceChromeBundle = typeof PRACTICES_EXPERIENCE_CHROME_RU | typeof PRACTICES_EXPERIENCE_CHROME_EN;

export function practicesExperienceChromeBundle(locale: FlowPracticesChromeLocale): PracticesExperienceChromeBundle {
  return locale === "ru" ? PRACTICES_EXPERIENCE_CHROME_RU : PRACTICES_EXPERIENCE_CHROME_EN;
}

/** Ключи streak-карточек Flow (зеркало `FlowTrackerChromeCopy.streakTitle`). */
export type FlowStreakKind =
  | "goal"
  | "state_phases"
  | "practice"
  | "habits"
  | "daily_signals"
  | "ritual"
  | "diary"
  | "affirmation";

export function flowStreakTitle(locale: FlowPracticesChromeLocale, key: string): string {
  const ru = locale === "ru";
  const map: Record<FlowStreakKind, [string, string]> = {
    goal: ["Цели", "Goals"],
    state_phases: ["Отметки", "Check-ins"],
    practice: ["Практики", "Practices"],
    habits: ["Привычки", "Habits"],
    daily_signals: ["Сигналы", "Signals"],
    ritual: ["Ритуал", "Ritual"],
    diary: ["Дневник", "Journal"],
    affirmation: ["Аффирмации", "Affirmations"],
  };
  if (key in map) {
    const pair = map[key as FlowStreakKind];
    return ru ? pair[0] : pair[1];
  }
  return key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function flowHabitWeekTarget(locale: FlowPracticesChromeLocale, n: number): string {
  return locale === "ru" ? `Цель: ${n} раза за неделю` : `Target: ${n}× per week`;
}

/** Story line for weekly rhythm — no completion % (Product Model §5.8). */
export function formatWeeklyRhythmStoryLine(
  locale: FlowPracticesChromeLocale,
  completionRate: number,
): string {
  const r = Math.max(0, Math.min(1, completionRate));
  if (locale === "ru") {
    if (r >= 0.75) return "Ритм на картах держится";
    if (r >= 0.45) return "История складывается — есть отметки и паузы";
    return "Мягкий ритм — узор только начинается";
  }
  if (r >= 0.75) return "Your map rhythm is holding steady";
  if (r >= 0.45) return "The story is taking shape—marks and pauses both count";
  return "A gentle rhythm—the pattern is just beginning";
}

/** Story line for habit map — no completion % (Product Model §5.8). */
export function formatHabitMapStatsLine(locale: FlowPracticesChromeLocale, streakDays: number): string {
  if (locale === "ru") {
    if (streakDays >= 14) return `${streakDays} дней подряд — узор на карте уже заметен`;
    if (streakDays >= 7) return `${streakDays} дней подряд — история складывается`;
    if (streakDays >= 1) {
      const dayWord = streakDays === 1 ? "день" : streakDays < 5 ? "дня" : "дней";
      return `${streakDays} ${dayWord} подряд на карте`;
    }
    return "Первые отметки — узор только начинается";
  }
  if (streakDays >= 14) return `${streakDays} days in a row—the weave on your map is showing`;
  if (streakDays >= 7) return `${streakDays} days in a row—your story is taking shape`;
  if (streakDays >= 1) return `${streakDays} day${streakDays === 1 ? "" : "s"} marked on the map`;
  return "First marks—the pattern is just beginning";
}

export function flowWeekFrom(locale: FlowPracticesChromeLocale, date: string): string {
  return locale === "ru" ? `Неделя с ${date}` : `Week from ${date}`;
}

export function flowMonthFrom(locale: FlowPracticesChromeLocale, date: string): string {
  return locale === "ru" ? `Месяц с ${date}` : `Month from ${date}`;
}

export type FlowAsceticDurationRaw = "open" | "d7" | "d14" | "d21" | "d30" | string;

export function flowAsceticDurationTitle(locale: FlowPracticesChromeLocale, raw: FlowAsceticDurationRaw): string {
  const ru = locale === "ru";
  switch (raw) {
    case "open":
      return ru ? "Без фиксированного срока" : "No fixed end";
    case "d7":
      return ru ? "7 дней" : "7 days";
    case "d14":
      return ru ? "14 дней" : "14 days";
    case "d21":
      return ru ? "21 день" : "21 days";
    case "d30":
      return ru ? "30 дней" : "30 days";
    default:
      return raw;
  }
}

export function practicesDayLine(locale: FlowPracticesChromeLocale, day: number): string {
  return locale === "ru" ? `День ${day}` : `Day ${day}`;
}

export function practicesUsedCount(locale: FlowPracticesChromeLocale, n: number): string {
  return locale === "ru" ? `использовано ${n}` : `used ${n}`;
}

export function practicesWeekWith(locale: FlowPracticesChromeLocale, date: string): string {
  return locale === "ru" ? `Неделя с ${date}` : `Week of ${date}`;
}

export function practicesCount(locale: FlowPracticesChromeLocale, n: number): string {
  return locale === "ru" ? `${n} практик` : `${n} practices`;
}

export function practicesSequenceStep(locale: FlowPracticesChromeLocale, step: number): string {
  return locale === "ru" ? `Серия · шаг ${step}` : `Sequence · step ${step}`;
}

export function practicesStepLine(locale: FlowPracticesChromeLocale, n: number, title: string): string {
  return locale === "ru" ? `Шаг ${n}. ${title}` : `Step ${n}. ${title}`;
}

export function practicesCompleteStep(locale: FlowPracticesChromeLocale, n: number): string {
  return locale === "ru" ? `Завершить шаг ${n}` : `Complete step ${n}`;
}

export function practicesNextStep(locale: FlowPracticesChromeLocale, name: string): string {
  return locale === "ru" ? `Следующий шаг: ${name}` : `Next: ${name}`;
}

/** Зеркало `PracticesExperienceChromeCopy.daysStreak`. */
export function practicesDaysStreak(locale: FlowPracticesChromeLocale, days: number): string {
  const ru = locale === "ru";
  if (days === 0) return ru ? "0 дней" : "0 days";
  if (!ru) return days === 1 ? "1 day" : `${days} days`;
  const n = Math.abs(days) % 100;
  const last = n % 10;
  let word: string;
  if (last === 1 && n !== 11) word = "день";
  else if ([2, 3, 4].includes(last) && !(n >= 12 && n <= 14)) word = "дня";
  else word = "дней";
  return `${days} ${word}`;
}

export function practicesCategoryDisplay(locale: FlowPracticesChromeLocale, raw: string): string {
  const ru = locale === "ru";
  switch (raw.toLowerCase()) {
    case "meditation":
      return ru ? "Медитация" : "Meditation";
    case "breathing":
      return ru ? "Дыхание" : "Breathing";
    case "gratitude":
      return ru ? "Благодарность" : "Gratitude";
    case "affirmation":
      return ru ? "Аффирмация" : "Affirmation";
    case "ritual":
      return ru ? "Ритуал" : "Ritual";
    case "reflection":
      return ru ? "Рефлексия" : "Reflection";
    case "emotional":
    case "emotions":
      return ru ? "Эмоции" : "Emotions";
    case "focus":
      return ru ? "Фокус" : "Focus";
    default:
      return raw.charAt(0).toUpperCase() + raw.slice(1);
  }
}

export function practicesDifficultyDisplay(locale: FlowPracticesChromeLocale, raw: string): string {
  const ru = locale === "ru";
  switch (raw.toLowerCase()) {
    case "easy":
    case "beginner":
      return ru ? "Лёгкая" : "Easy";
    case "medium":
    case "intermediate":
      return ru ? "Средняя" : "Medium";
    case "hard":
    case "advanced":
      return ru ? "Сложная" : "Hard";
    default:
      return raw.charAt(0).toUpperCase() + raw.slice(1);
  }
}
