export const TODAY_CONTRACT_COPY = {
  periodEyebrow: "Период дня",
  growthEyebrow: "Личный рост",
  narrativeMainEyebrow: "Главная мысль дня",
  narrativeManifestationsEyebrow: "Где это проявится",
  experienceSynthesisEyebrow: "Твой день сегодня",
  experienceAttentionEyebrow: "Обрати внимание",
  experienceHelpEyebrow: "Что может помочь",
  experienceDoubtEyebrow: "Что поставить под сомнение",
  experienceQuestionEyebrow: "Вопрос дня",
  experiencePersonalEyebrow: "Личное наблюдение",
  experienceEveningEyebrow: "Вечером",
  primaryActionEyebrow: "Что сделать",
  domainRelationships: "Отношения",
  domainMoneyWork: "Работа и деньги",
  domainFamily: "Семья",
  slotStatus: "Статус",
  slotOpportunity: "Возможность",
  slotRisk: "Риск",
  slotAction: "Действие",
  slotFamilyOpportunity: "Поддержка",
  slotFamilyRisk: "Напряжение",
  loading: "Собираю навигацию дня…",
  loadError: "Не удалось загрузить Today. Попробуй обновить страницу.",
} as const;
