/** User-facing copy for Today Day Story — ritual-first day assembly. */

export const TODAY_COMPOSITION_COPY = {
  foundationLabel: "Основа дня",
  pulseLabel: "Энергия дня",
  foundationEyebrow: "Сегодняшняя основа дня",
  glanceStrongTitle: "Чего ожидать",
  glanceWeakTitle: "Ловушка дня",
  sphereNeutralNote: "",
  whyStoryTitle: "Почему сегодня именно так",
  astroContextTitle: "Сигналы дня",
  lunarContextTitle: "Лунный контекст",
  expectLabel: "Чего ожидать",
  trapLabel: "Ловушка дня",
  doLabel: "Что делать",
  avoidLabel: "Чего не делать",
  vibeLabel: "Общий вайб",
  conflictLabel: "Главный сюжет дня",
  eventsLeadLabel: "Что происходит на небе",
  instructionTitle: "Инструкция дня",
  ritualTarotPendingTitle: "Давай вытащим карту дня",
  ritualTarotPendingBody:
    "Не ответ на все вопросы — скорее зеркало. Выбери ту, к которой тянет, и посмотрим, что она говорит о сегодня.",
  ritualTarotPickCta: "Выбрать карту",
  ritualTarotOpenCta: "Открыть карту",
  ritualNumberPendingTitle: "Теперь — число дня",
  ritualNumberPendingBody:
    "Оно задаёт ритм: когда лучше действовать, а когда — не торопиться. Откроем и посмотрим.",
  ritualNumberPickCta: "Выбрать число",
  ritualNumberOpenCta: "Открыть число дня",
  ritualIncompleteHint: "Карта и число — дополнительный слой поверх уже собранного дня.",
  strengthenTitle: "Что сегодня поможет именно тебе",
  promiseTitle: "Какое обещание ты хочешь дать себе сегодня?",
  promiseLead: "Сегодня я…",
  promiseUnsetHint: "Маленькое обещание помогает завершить день осмысленно — выбери, если откликается.",
  promiseSave: "Выбрать обещание",
  goalPrompt: "Своё обещание на сегодня",
  goalSave: "Сохранить обещание",
  actionsTitle: "Сделай сегодняшний день своим",
  actionsLead: "Сегодня можно:",
  growthTitle: "Твоя история",
  continuityNoteTitle: "Твоя история",
  continuityEyebrow: "С чего продолжить",
  loadingDay: "Слушаю, как звучит твой день…",
  eveningHint: "Когда будешь готов — подведём итог: получилось / частично / не получилось.",
  eveningCta: "Закрыть день",
  eveningRecapTitle: "Перед тем как завершить",
  practiceStart: "Начать практику",
  practiceStarted: "Практика запущена",
  practiceComplete: "Завершить практику",
  practiceCompleted: "Практика выполнена",
  readAffirmation: "Прочитать",
  markAffirmationDone: "Сделал(а)",
  affirmationDone: "Аффирмация отмечена",
  markHabitDone: "Отметил(а) сегодня",
  habitDone: "Привычка отмечена",
  markAsceticDone: "Отметил(а) сегодня",
  asceticDone: "Аскеза отмечена",
  setupPracticesLink: "Настроить привычку или практику",
  themeLabel: "Главная тема дня",
  ritualSpineTitle: "Твой ритуал дня",
  ritualSpineLead: "Два шага — и Today соберёт рекомендации под тебя.",
  contextPanelTitle: "Контекст дня",
  /** Journey scene chrome — same family as Profile · Wave 1 ActShell. */
  journey: {
    dayTitle: "Сюжет дня",
    dayLead: "Одна главная линия — что держит день вместе.",
    openTitle: "Символы дня",
    openLead: "Карта и число — ритуал раскрытия. Цвет идёт вместе с картой. Не пересобирают день.",
    readingTitle: "Как проживать день",
    readingTitleStory: "История дня",
    readingLead: "До двух сфер с реальным сигналом — сначала почему, потом сцена.",
    readingSphereWhyLabel: "Почему эта сфера сегодня",
    readingExpandLabel: "Сцена · возможность и ловушка",
    sceneOpportunityLabel: "Возможность",
    sceneTrapLabel: "Ловушка",
    moveTitle: "Сделать день своим",
    moveLead: "Одно обещание и одна опора — без перегруза.",
    moveIfThenEyebrow: "Если / то",
    moveDoLabel: "Сегодня сработает",
    moveAvoidLabel: "Сегодня лучше не",
    bridgeTitle: "Продолжение",
    bridgeLead: "Короткий отклик сегодня — точнее завтра.",
    tapStubLabel: "Сбылось ли главное сегодня?",
    tapStubHint: "Wave 2: точность дня. Пока отметь для себя.",
    tapQuestion: "Ловушка дня — удалось ли обойти?",
    tapAvoided: "Обошёл",
    tapFell: "Попал",
    tapNotApplicable: "Не про это",
    tapRecorded: "Учли — это копит твою точность.",
    tapError: "Не удалось сохранить. Попробуй ещё раз.",
    tapEmptyHint: "Сегодня без острой ловушки.",
    verdictSlotHint: "",
    verdictStripLabel: "Сферы дня",
    glanceSlotHint: "",
    glanceStripLabel: "Моменты дня",
    glanceTitle: "Сводка дня",
    glanceLead: "Что сегодня ждать — коротко. Дальше — ритуал крючков.",
    glanceTeasersLabel: "Дальше в дне",
    glanceNow: "сейчас",
    /** House label for texture Block — mockup mood (FOUNDATION_UI §16), not short_name. */
    glanceThemeLabel: "Тема дня",
    glanceNearestLabel: "Ближайшее окно",
    glanceNearestEmpty: "Ближайшее окно сегодня не выделено.",
    glanceNearestPracticeHint: "практика →",
    /** One Daily Focus — replaces legacy «Сферы дня» chips (R15–R17). */
    glanceFocusLabel: "Фокус дня",
    glanceFocusPrioritize: "В приоритете · ",
    glanceFocusAvoid: "Избегать · ",
    /** @deprecated Prefer glanceFocusLabel — kept for mid-migration strings. */
    glanceSpheresLabel: "Фокус дня",
    teaserPlotHook: "одна линия, что держит день",
    teaserSymbolsHook: "карта и число дня",
    actNavGlance: "Приветствие",
    actNavPlot: "Инсайт",
    actNavSymbols: "Символы",
    actNavReading: "Опора",
    actNavMove: "Практика",
    actNavBridge: "Вечер",
  },
} as const;
