/** User-facing copy for Today Day Story — ritual-first day assembly. */

export const TODAY_COMPOSITION_COPY = {
  foundationLabel: "Основа дня",
  pulseLabel: "Энергия дня",
  foundationEyebrow: "Сегодняшняя основа дня",
  glanceStrongTitle: "Где день теплее",
  glanceWeakTitle: "Где лучше не торопиться",
  sphereNeutralNote: "",
  whyStoryTitle: "Почему сегодня именно так",
  astroContextTitle: "Астрологический контекст",
  lunarContextTitle: "Лунный контекст",
  ritualTarotPendingTitle: "Давай вытащим карту дня",
  ritualTarotPendingBody:
    "Не ответ на все вопросы — скорее зеркало. Выбери ту, к которой тянет, и посмотрим, что она говорит о сегодня.",
  ritualTarotPickCta: "Выбрать карту",
  ritualTarotOpenCta: "Открыть карту",
  ritualNumberPendingTitle: "Теперь — число дня",
  ritualNumberPendingBody:
    "Оно задаёт ритм: когда лучше действовать, а когда — не торопиться. Откроем и посмотрим.",
  ritualNumberPickCta: "Выбрать число",
  ritualNumberOpenCta: "Открыть число дня",
  ritualIncompleteHint: "Карта и число — и день соберётся под тебя.",
  strengthenTitle: "Что сегодня поможет именно тебе",
  promiseTitle: "Какое обещание ты хочешь дать себе сегодня?",
  promiseLead: "Сегодня я…",
  promiseUnsetHint: "Маленькое обещание помогает завершить день осмысленно — выбери, если откликается.",
  promiseSave: "Выбрать обещание",
  goalPrompt: "Своё обещание на сегодня",
  goalSave: "Сохранить обещание",
  actionsTitle: "Сделай сегодняшний день своим",
  actionsLead: "Сегодня можно:",
  growthTitle: "Твоя история",
  continuityNoteTitle: "Твоя история",
  continuityEyebrow: "С чего продолжить",
  loadingDay: "Слушаю, как звучит твой день…",
  eveningHint: "Когда будешь готов — подведём итог вместе.",
  eveningCta: "Закрыть день",
  eveningRecapTitle: "Перед тем как завершить",
  practiceStart: "Начать практику",
  practiceStarted: "Практика запущена",
  practiceComplete: "Завершить практику",
  practiceCompleted: "Практика выполнена",
  readAffirmation: "Прочитать",
  markAffirmationDone: "Сделал(а)",
  affirmationDone: "Аффирмация отмечена",
  markHabitDone: "Отметил(а) сегодня",
  habitDone: "Привычка отмечена",
  markAsceticDone: "Отметил(а) сегодня",
  asceticDone: "Аскеза отмечена",
  setupPracticesLink: "Настроить привычку или практику",
  themeLabel: "Главная тема дня",
  ritualSpineTitle: "Твой ритуал дня",
  ritualSpineLead: "Два шага — и Today соберёт рекомендации под тебя.",
  contextPanelTitle: "Контекст дня",
  /** Journey scene chrome — same family as Profile. */
  journey: {
    dayTitle: "Суть дня",
    dayLead: "Короткая тема. Карта и число откроешь сам — они станут слоем смысла, не подсказкой заранее.",
    openTitle: "Открыть день",
    openLead: "Карта и число — интерпретационный слой. Выбери их, и история соберётся под тебя.",
    readingTitle: "История дня",
    readingLead:
      "Рассказ дня: небо и переходы, как это на тебя ложится, что усиливает и ослабляет — и слой открытой карты с числом.",
    moveTitle: "Твой ход",
    moveLead: "Цель и практики — из того, что уже звучит в истории дня.",
    bridgeTitle: "Продолжение",
    bridgeLead: "День связан с картой личности и темами, которые можно углубить.",
  },
} as const;
